export const DEFENSIBLE_MISS_DISCLAIMER =
  'Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.';

export interface FlankingSampleRef {
  lab_result_id: string;
  sample_date: string;
  result_value: number | null;
  result_text: string | null;
  unit: string | null;
  is_non_detect: boolean;
  analyzed_date: string | null;
}

export interface DefensibleMissPacket {
  gap_id: string;
  outfall_id: string;
  parameter_id: string;
  scheduled_date: string;
  days_late: number;
  before_sample: FlankingSampleRef | null;
  after_sample: FlankingSampleRef | null;
  defense_note: string;
}

export interface CollectorAccessAnomaly {
  collector_id: string;
  collector_name: string;
  access_issue_count: number;
  no_discharge_count: number;
  completed_visits: number;
  access_issue_rate_pct: number;
}

export function formatDefensibleMissMarkdown(
  packet: DefensibleMissPacket,
  outfallLabel: string,
  parameterLabel: string,
): string {
  const lines = [
    '# Defensible-Miss Packet (DRAFT — counsel review only)',
    '',
    `**Miss date:** ${packet.scheduled_date}`,
    `**Outfall:** ${outfallLabel}`,
    `**Parameter:** ${parameterLabel}`,
    `**Days late:** ${packet.days_late}`,
    '',
    '## Flanking clean sample — before',
    formatSampleBlock(packet.before_sample),
    '',
    '## Flanking clean sample — after',
    formatSampleBlock(packet.after_sample),
    '',
    `> ${packet.defense_note}`,
    '',
    DEFENSIBLE_MISS_DISCLAIMER,
  ];
  return lines.join('\n');
}

function formatSampleBlock(sample: FlankingSampleRef | null): string {
  if (!sample) return '_No qualifying clean sample found in platform data._';
  const value = sample.is_non_detect
    ? 'Non-detect'
    : sample.result_value ?? sample.result_text ?? '—';
  return [
    `- Sample date: ${sample.sample_date}`,
    `- Analyzed: ${sample.analyzed_date ?? '—'}`,
    `- Result: ${value} ${sample.unit ?? ''}`.trim(),
  ].join('\n');
}
