export const DISCLAIMER_FULL = `SOFTWARE DISCLAIMER & LIMITATION OF LIABILITY
Compliance Monitoring & Reporting Software

IMPORTANT NOTICE: This software is a compliance monitoring and reporting tool. It is NOT an Environmental Management System (EMS), does NOT constitute environmental consulting, and does NOT replace the professional judgment of licensed environmental engineers, certified professionals, or qualified legal counsel.

1. Nature of Software
This software application (the "Software") is a data management, monitoring, and reporting tool designed to assist organizations in tracking and organizing environmental compliance data. The Software automates data entry workflows, compares laboratory results against user-defined permit limits, generates alerts for potential exceedances, and produces formatted reports for internal review. The Software is a tool that facilitates compliance workflows. It does not independently evaluate, interpret, or certify environmental compliance status. All permit limits, regulatory thresholds, and reporting parameters are defined and entered by the user or the user's qualified personnel. The Software applies those user-defined parameters to organize and present data — it does not determine what those parameters should be.

2. What This Software Is NOT
This Software is NOT any of the following, and shall not be construed, represented, or relied upon as such:

a. An Environmental Management System (EMS). The Software does not constitute an EMS as defined by ISO 14001, EPA guidance, or any federal, state, or local regulatory framework. It does not establish environmental policies, set organizational objectives, assign management responsibilities, or define corrective action procedures. Organizations subject to Consent Decrees, settlement agreements, or regulatory orders requiring implementation of an EMS must develop and maintain their own EPA-approved EMS independently of this Software.

b. Environmental Consulting. The Software does not provide environmental consulting services, professional advice, regulatory interpretations, or compliance recommendations. It does not assess the adequacy of treatment systems, evaluate the sufficiency of monitoring programs, or advise on corrective actions for permit violations.

c. Legal Advice or Legal Compliance Certification. The Software does not provide legal advice, interpret Consent Decree obligations, or certify that any organization is in compliance with the Clean Water Act, NPDES permit requirements, or any other federal, state, or local environmental law or regulation. Use of this Software does not create an attorney-client relationship or a professional consulting engagement.

d. A Substitute for Qualified Personnel. The Software does not replace the need for licensed Professional Engineers, Certified Hazardous Materials Managers, qualified environmental scientists, or other credentialed professionals required by applicable regulations to oversee environmental compliance programs, sign Discharge Monitoring Reports, or certify regulatory submissions.

3. User Responsibilities
The user is solely responsible for the accuracy of all data entered into the Software, including but not limited to permit limits, parameter thresholds, outfall designations, sampling schedules, and laboratory results. The user is solely responsible for verifying all reports generated by the Software before submission to any regulatory agency. The user is solely responsible for ensuring that all regulatory submissions are reviewed, approved, and signed by appropriately qualified and authorized personnel as required by applicable law.

4. No Warranty of Regulatory Compliance
The Software is provided "as is" without warranty that its use will result in compliance with any environmental law, regulation, permit, Consent Decree, or settlement agreement. The developer makes no representation or warranty, express or implied, that data processed through the Software is complete, accurate, or sufficient to satisfy any regulatory obligation. The user acknowledges that environmental regulations are subject to change and that the Software may not reflect the most current regulatory requirements at any given time.

5. Limitation of Liability
To the maximum extent permitted by applicable law, the developer shall not be liable for any fines, penalties, stipulated penalties, injunctive relief costs, remediation costs, enforcement actions, or other damages arising from the user's reliance on the Software for environmental compliance purposes. The developer's total liability under any theory of liability shall not exceed the fees paid by the user for the Software during the twelve (12) months preceding the event giving rise to the claim.

6. Indemnification
The user agrees to indemnify, defend, and hold harmless the developer from and against any claims, damages, losses, penalties, fines, or expenses (including reasonable attorney's fees) arising from or related to the user's use of the Software, the user's failure to independently verify data or reports generated by the Software, or the user's failure to comply with applicable environmental laws and regulations.

7. Recommendation
Users are strongly encouraged to consult with qualified environmental professionals and legal counsel to ensure that their compliance programs meet all applicable regulatory requirements. This Software is designed to support — not replace — professional compliance management.`;

export const DISCLAIMER_SHORT = `This software is a compliance monitoring and reporting tool only. It is not an Environmental Management System (EMS), does not provide environmental consulting or legal advice, and does not certify regulatory compliance. All data, permit limits, and reporting parameters are defined by the user. All reports must be independently verified by qualified personnel before regulatory submission. Use of this software does not replace the need for licensed environmental professionals or legal counsel.`;

export const DISCLAIMER_EXPORT = `Generated by SCC Compliance Monitor \u2014 a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.`;
