import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

// ---------------------------------------------------------------------------
// Inline CORS (MCP deploy cannot resolve _shared imports)
// ---------------------------------------------------------------------------
const ALLOWED_ORIGIN = Deno.env.get("FRONTEND_URL") ?? (
  (Deno.env.get("SUPABASE_URL") ?? "").includes("localhost") ? "http://localhost:5173" : ""
);

const corsHeaders = {
  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-internal-secret",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY =
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

const DISCLAIMER_ONELINER =
  "Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface EvidenceData {
  event_id: string;
  event_date: string;
  rainfall_inches: number;
  trigger_source: string;
  status: string;
  station_id: string;
  station_name: string;
  station_type: string;
  weather_station_id: string;
  organization_name: string;
  activated_by_name: string | null;
  activated_at: string | null;
  dismissed_by_name: string | null;
  dismissed_at: string | null;
  dismiss_reason_code: string | null;
  dismiss_justification: string | null;
  manual_trigger_reason_code: string | null;
  manual_trigger_justification: string | null;
  recurrence_interval: number | null;
  readings: {
    reading_date: string;
    rainfall_inches: number;
    source_type: string;
    data_quality_flag: string | null;
  }[];
  affected_outfalls: {
    outfall_number: string;
    permit_number: string;
    site_name: string;
  }[];
  sampling_events: {
    outfall_number: string;
    status: string;
    collected_at: string | null;
  }[];
}

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------
async function verifyAuth(
  req: Request,
  supabase: ReturnType<typeof createClient>
): Promise<{ userId: string | null; orgId: string | null }> {
  const authHeader = req.headers.get("Authorization");
  if (!authHeader?.startsWith("Bearer ")) {
    return { userId: null, orgId: null };
  }

  const token = authHeader.replace("Bearer ", "");
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser(token);

  if (error || !user) return { userId: null, orgId: null };

  const { data: profile } = await supabase
    .from("user_profiles")
    .select("organization_id")
    .eq("id", user.id)
    .single();

  return {
    userId: user.id,
    orgId: profile?.organization_id ?? null,
  };
}

// ---------------------------------------------------------------------------
// PDF Helpers
// ---------------------------------------------------------------------------
function formatDate(dateStr: string | null): string {
  if (!dateStr) return "N/A";
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZoneName: "short",
  });
}

function drawLine(
  page: ReturnType<InstanceType<typeof PDFDocument>["addPage"]>,
  font: Awaited<ReturnType<InstanceType<typeof PDFDocument>["embedFont"]>>,
  y: number,
  label: string,
  value: string,
  width: number
): number {
  const lineHeight = 16;
  const labelWidth = 200;

  page.drawText(label, {
    x: 50,
    y,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  // Word wrap the value
  const maxValueWidth = width - 260;
  const words = value.split(" ");
  let currentLine = "";
  let currentY = y;

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const testWidth = font.widthOfTextAtSize(testLine, 9);
    if (testWidth > maxValueWidth && currentLine) {
      page.drawText(currentLine, {
        x: 50 + labelWidth,
        y: currentY,
        size: 9,
        font,
        color: rgb(0.1, 0.1, 0.1),
      });
      currentY -= lineHeight;
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }

  if (currentLine) {
    page.drawText(currentLine, {
      x: 50 + labelWidth,
      y: currentY,
      size: 9,
      font,
      color: rgb(0.1, 0.1, 0.1),
    });
  }

  return currentY - lineHeight - 2;
}

// ---------------------------------------------------------------------------
// SHA-256 hash
// ---------------------------------------------------------------------------
async function sha256Hash(data: Uint8Array): Promise<string> {
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ---------------------------------------------------------------------------
// Generate PDF
// ---------------------------------------------------------------------------
async function generateEvidencePDF(
  evidence: EvidenceData
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 612; // Letter
  const pageHeight = 792;
  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - 60;

  // Title
  page.drawText("PRECIPITATION EVENT EVIDENCE PACKET", {
    x: 50,
    y,
    size: 16,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.15),
  });
  y -= 12;
  page.drawText("SCC Compliance Monitoring System — Court-Defensible Record", {
    x: 50,
    y,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });
  y -= 25;

  // Separator
  page.drawRectangle({
    x: 50,
    y,
    width: pageWidth - 100,
    height: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  y -= 20;

  // Section: Event Details
  page.drawText("1. EVENT DETAILS", {
    x: 50,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.15, 0.2),
  });
  y -= 18;

  y = drawLine(page, font, y, "Event ID:", evidence.event_id, pageWidth);
  y = drawLine(page, font, y, "Event Date:", formatDate(evidence.event_date), pageWidth);
  y = drawLine(page, font, y, "Rainfall Amount:", `${evidence.rainfall_inches}" (inches)`, pageWidth);
  y = drawLine(page, font, y, "Trigger Source:", evidence.trigger_source, pageWidth);
  y = drawLine(page, font, y, "Status:", evidence.status.toUpperCase(), pageWidth);
  y = drawLine(page, font, y, "Organization:", evidence.organization_name, pageWidth);

  if (evidence.recurrence_interval) {
    y = drawLine(page, font, y, "Recurrence Interval:", `${evidence.recurrence_interval}-year storm`, pageWidth);
  }

  y -= 10;

  // Section: Weather Station
  page.drawText("2. WEATHER STATION", {
    x: 50,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.15, 0.2),
  });
  y -= 18;

  y = drawLine(page, font, y, "Station ID:", evidence.station_id, pageWidth);
  y = drawLine(page, font, y, "Station Name:", evidence.station_name, pageWidth);
  y = drawLine(page, font, y, "Station Type:", evidence.station_type, pageWidth);
  y -= 10;

  // Section: Raw Data
  page.drawText("3. PRECIPITATION READINGS", {
    x: 50,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.15, 0.2),
  });
  y -= 18;

  if (evidence.readings.length === 0) {
    y = drawLine(page, font, y, "Readings:", "No associated readings found", pageWidth);
  } else {
    for (const r of evidence.readings.slice(0, 15)) {
      const flag = r.data_quality_flag ? ` [${r.data_quality_flag}]` : "";
      y = drawLine(
        page,
        font,
        y,
        r.reading_date,
        `${r.rainfall_inches}" — Source: ${r.source_type}${flag}`,
        pageWidth
      );

      // New page if needed
      if (y < 80) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        y = pageHeight - 60;
      }
    }
  }
  y -= 10;

  // Section: Decision Record
  if (y < 200) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    y = pageHeight - 60;
  }

  page.drawText("4. DECISION RECORD", {
    x: 50,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.15, 0.2),
  });
  y -= 18;

  if (evidence.activated_by_name) {
    y = drawLine(page, font, y, "Activated By:", evidence.activated_by_name, pageWidth);
    y = drawLine(page, font, y, "Activated At:", formatDate(evidence.activated_at), pageWidth);
  }

  if (evidence.dismissed_by_name) {
    y = drawLine(page, font, y, "Dismissed By:", evidence.dismissed_by_name, pageWidth);
    y = drawLine(page, font, y, "Dismissed At:", formatDate(evidence.dismissed_at), pageWidth);
    y = drawLine(page, font, y, "Dismiss Reason:", evidence.dismiss_reason_code ?? "N/A", pageWidth);
    y = drawLine(page, font, y, "Justification:", evidence.dismiss_justification ?? "N/A", pageWidth);
  }

  if (evidence.manual_trigger_reason_code) {
    y = drawLine(page, font, y, "Manual Trigger:", evidence.manual_trigger_reason_code, pageWidth);
    y = drawLine(page, font, y, "Trigger Justification:", evidence.manual_trigger_justification ?? "N/A", pageWidth);
  }
  y -= 10;

  // Section: Affected Outfalls
  if (y < 150) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    y = pageHeight - 60;
  }

  page.drawText("5. AFFECTED OUTFALLS", {
    x: 50,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.15, 0.2),
  });
  y -= 18;

  if (evidence.affected_outfalls.length === 0) {
    y = drawLine(page, font, y, "Outfalls:", "No outfalls linked to this event", pageWidth);
  } else {
    for (const o of evidence.affected_outfalls) {
      y = drawLine(
        page,
        font,
        y,
        `Outfall ${o.outfall_number}:`,
        `${o.site_name} — Permit ${o.permit_number}`,
        pageWidth
      );
      if (y < 80) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        y = pageHeight - 60;
      }
    }
  }
  y -= 10;

  // Section: Sampling Status
  if (y < 150) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    y = pageHeight - 60;
  }

  page.drawText("6. SAMPLING STATUS", {
    x: 50,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.15, 0.2),
  });
  y -= 18;

  if (evidence.sampling_events.length === 0) {
    y = drawLine(page, font, y, "Sampling:", "No sampling events linked", pageWidth);
  } else {
    for (const s of evidence.sampling_events) {
      y = drawLine(
        page,
        font,
        y,
        `Outfall ${s.outfall_number}:`,
        `${s.status} — ${s.collected_at ? formatDate(s.collected_at) : "Not collected"}`,
        pageWidth
      );
      if (y < 80) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        y = pageHeight - 60;
      }
    }
  }

  // Footer disclaimer on last page
  if (y < 120) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    y = pageHeight - 60;
  }

  y = 50;
  page.drawRectangle({
    x: 50,
    y: y + 5,
    width: pageWidth - 100,
    height: 1,
    color: rgb(0.8, 0.8, 0.8),
  });

  page.drawText(DISCLAIMER_ONELINER, {
    x: 50,
    y: y - 10,
    size: 6,
    font,
    color: rgb(0.5, 0.5, 0.5),
    maxWidth: pageWidth - 100,
  });

  page.drawText(
    `Generated: ${new Date().toISOString()} | Document hash computed after generation`,
    {
      x: 50,
      y: y - 22,
      size: 6,
      font,
      color: rgb(0.6, 0.6, 0.6),
    }
  );

  return await pdfDoc.save();
}

// ---------------------------------------------------------------------------
// Main Handler
// ---------------------------------------------------------------------------
serve(async (req: Request) => {
  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const serviceClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Auth check
    const { userId, orgId } = await verifyAuth(req, serviceClient);
    if (!userId) {
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Parse request
    const { event_id } = await req.json();
    if (!event_id) {
      return new Response(
        JSON.stringify({ error: "event_id is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fetch the precipitation event
    const { data: event, error: eventErr } = await serviceClient
      .from("precipitation_events")
      .select("*")
      .eq("id", event_id)
      .single();

    if (eventErr || !event) {
      return new Response(
        JSON.stringify({ error: "Event not found" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fetch weather station
    const { data: station } = await serviceClient
      .from("weather_stations")
      .select("station_id, station_name, station_type")
      .eq("id", event.weather_station_id)
      .single();

    // Fetch organization name
    let orgName = "Unknown Organization";
    if (event.organization_id) {
      const { data: org } = await serviceClient
        .from("organizations")
        .select("name")
        .eq("id", event.organization_id)
        .single();
      if (org) orgName = org.name;
    }

    // Fetch user profiles for activated_by / dismissed_by
    let activatedByName: string | null = null;
    if (event.activated_by) {
      const { data: profile } = await serviceClient
        .from("user_profiles")
        .select("first_name, last_name")
        .eq("id", event.activated_by)
        .single();
      if (profile) activatedByName = `${profile.first_name} ${profile.last_name}`;
    }

    let dismissedByName: string | null = null;
    if (event.dismissed_by) {
      const { data: profile } = await serviceClient
        .from("user_profiles")
        .select("first_name, last_name")
        .eq("id", event.dismissed_by)
        .single();
      if (profile) dismissedByName = `${profile.first_name} ${profile.last_name}`;
    }

    // Fetch related precipitation readings (7 days around event)
    const eventDate = new Date(event.event_date ?? event.event_start ?? event.created_at);
    const startDate = new Date(eventDate.getTime() - 7 * 86_400_000).toISOString().slice(0, 10);
    const endDate = new Date(eventDate.getTime() + 7 * 86_400_000).toISOString().slice(0, 10);

    const { data: readings } = await serviceClient
      .from("precipitation_readings")
      .select("reading_date, rainfall_inches, source_type, data_quality_flag")
      .eq("weather_station_id", event.weather_station_id)
      .gte("reading_date", startDate)
      .lte("reading_date", endDate)
      .order("reading_date", { ascending: true });

    // Fetch affected outfalls via sampling_events linked to this precipitation event
    const { data: samplingEvents } = await serviceClient
      .from("sampling_events")
      .select("id, outfall_id, status, collection_date, outfalls!inner(outfall_number, site_id, permit_id, sites!inner(name), npdes_permits!inner(permit_number))")
      .eq("precipitation_event_id", event_id);

    const affectedOutfalls = (samplingEvents ?? []).map((se: Record<string, unknown>) => {
      const outfall = se.outfalls as Record<string, unknown> | null;
      return {
        outfall_number: (outfall?.outfall_number as string) ?? "Unknown",
        permit_number: ((outfall?.npdes_permits as Record<string, unknown>)?.permit_number as string) ?? "Unknown",
        site_name: ((outfall?.sites as Record<string, unknown>)?.name as string) ?? "Unknown",
      };
    });

    const samplingStatus = (samplingEvents ?? []).map((se: Record<string, unknown>) => {
      const outfall = se.outfalls as Record<string, unknown> | null;
      return {
        outfall_number: (outfall?.outfall_number as string) ?? "Unknown",
        status: (se.status as string) ?? "unknown",
        collected_at: (se.collection_date as string) ?? null,
      };
    });

    // Build evidence data
    const evidenceData: EvidenceData = {
      event_id: event.id,
      event_date: event.event_date ?? event.event_start ?? event.created_at,
      rainfall_inches: event.rainfall_inches,
      trigger_source: event.trigger_source ?? "unknown",
      status: event.status,
      station_id: station?.station_id ?? "Unknown",
      station_name: station?.station_name ?? "Unknown",
      station_type: station?.station_type ?? "Unknown",
      weather_station_id: event.weather_station_id,
      organization_name: orgName,
      activated_by_name: activatedByName,
      activated_at: event.activated_at,
      dismissed_by_name: dismissedByName,
      dismissed_at: event.dismissed_at,
      dismiss_reason_code: event.dismiss_reason_code,
      dismiss_justification: event.dismiss_justification,
      manual_trigger_reason_code: event.manual_trigger_reason_code,
      manual_trigger_justification: event.manual_trigger_justification,
      recurrence_interval: event.recurrence_interval ? parseFloat(event.recurrence_interval) : null,
      readings: (readings ?? []) as EvidenceData["readings"],
      affected_outfalls: affectedOutfalls,
      sampling_events: samplingStatus,
    };

    // Generate PDF
    const pdfBytes = await generateEvidencePDF(evidenceData);
    const pdfData = new Uint8Array(pdfBytes);

    // Compute SHA-256 hash
    const docHash = await sha256Hash(pdfData);

    // Upload to precipitation-evidence storage bucket
    const fileName = `evidence_${event_id}_${Date.now()}.pdf`;
    const storagePath = `${orgId ?? "unknown"}/${fileName}`;

    const { error: uploadErr } = await serviceClient.storage
      .from("precipitation-evidence")
      .upload(storagePath, pdfData, {
        contentType: "application/pdf",
        upsert: false,
      });

    if (uploadErr) {
      console.error("[evidence-pdf] Upload error:", uploadErr.message);
      // Still return PDF even if storage upload fails
    }

    // Log to audit_log
    await serviceClient.from("audit_log").insert({
      user_id: userId,
      action: "precipitation_evidence_generated",
      details: {
        event_id,
        file_name: fileName,
        storage_path: storagePath,
        sha256_hash: docHash,
        upload_success: !uploadErr,
      },
    });

    // Return the PDF
    return new Response(pdfData, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
        "X-Document-Hash": docHash,
      },
    });
  } catch (err) {
    console.error("[evidence-pdf] Error:", err);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
