const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") ?? "";
const TWILIO_ACCOUNT_SID = Deno.env.get("TWILIO_ACCOUNT_SID") ?? "";
const TWILIO_AUTH_TOKEN = Deno.env.get("TWILIO_AUTH_TOKEN") ?? "";
const TWILIO_FROM_NUMBER = Deno.env.get("TWILIO_FROM_NUMBER") ?? "";
const RESEND_FROM = Deno.env.get("RESEND_FROM_EMAIL") ?? "SCC Compliance <compliance@scc-monitor.com>";

export const EXPORT_DISCLAIMER_HTML = `
  <p style="font-size: 11px; color: #64748b; margin-top: 16px; line-height: 1.5;">
    Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS.
    Not legal or environmental consulting. All data and reports require independent
    verification by qualified personnel before regulatory submission.
  </p>
`;

export function escapeHtml(v: string | number): string {
  return String(v)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}

export interface EmailSendResult {
  ok: boolean;
  skipped?: boolean;
  id?: string;
  error?: string;
}

export async function sendResendEmail(params: {
  to: string;
  subject: string;
  html: string;
}): Promise<EmailSendResult> {
  if (!RESEND_API_KEY) {
    console.log("[notification-dispatch] RESEND_API_KEY not set — skipping email");
    return { ok: true, skipped: true };
  }

  if (!isValidEmail(params.to)) {
    return { ok: false, error: "Invalid recipient email" };
  }

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: RESEND_FROM,
      to: [params.to.trim()],
      subject: params.subject,
      html: params.html,
    }),
  });

  const text = await res.text();
  let data: { id?: string; message?: string } = {};
  try {
    data = text ? JSON.parse(text) as typeof data : {};
  } catch {
    data = { message: text.slice(0, 200) };
  }

  if (!res.ok) {
    return { ok: false, error: data.message ?? `Resend HTTP ${res.status}` };
  }

  return { ok: true, id: data.id };
}

export interface SmsSendResult {
  ok: boolean;
  skipped?: boolean;
  sid?: string;
  error?: string;
}

/** E.164-ish validation (minimal). */
export function isValidSmsNumber(phone: string): boolean {
  const p = phone.trim();
  return /^\+[1-9]\d{7,14}$/.test(p);
}

export async function sendTwilioSms(params: {
  to: string;
  body: string;
}): Promise<SmsSendResult> {
  if (!TWILIO_ACCOUNT_SID || !TWILIO_AUTH_TOKEN || !TWILIO_FROM_NUMBER) {
    console.log("[notification-dispatch] Twilio env not set — skipping SMS");
    return { ok: true, skipped: true };
  }

  if (!isValidSmsNumber(params.to)) {
    return { ok: false, error: `Invalid SMS number: ${params.to}` };
  }

  const url =
    `https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/Messages.json`;
  const auth = btoa(`${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}`);
  const form = new URLSearchParams({
    From: TWILIO_FROM_NUMBER,
    To: params.to.trim(),
    Body: params.body.slice(0, 1500),
  });

  const res = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: form.toString(),
  });

  const data = await res.json() as { sid?: string; message?: string };
  if (!res.ok) {
    return { ok: false, error: data.message ?? `Twilio HTTP ${res.status}` };
  }

  return { ok: true, sid: data.sid };
}

export function parseOnCallSmsNumbers(): string[] {
  const raw = Deno.env.get("COMPLIANCE_ALERT_SMS_TO") ?? "";
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && isValidSmsNumber(s));
}

export function buildAlertEmailHtml(params: {
  title: string;
  body: string;
  actionLabel: string;
  actionHref: string;
  accentColor?: string;
}): string {
  const accent = params.accentColor ?? "#7c3aed";
  const bodyHtml = escapeHtml(params.body).replace(/\n/g, "<br/>");
  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: #1a1a2e; color: #f1f5f9; border-radius: 12px; padding: 24px; border: 1px solid ${accent}40;">
        <h2 style="margin: 0 0 12px; color: ${accent};">${escapeHtml(params.title)}</h2>
        <p style="font-size: 14px; line-height: 1.6; color: #cbd5e1;">${bodyHtml}</p>
        <div style="margin-top: 20px; padding-top: 16px; border-top: 1px solid #334155;">
          <a href="${escapeHtml(params.actionHref)}" style="display: inline-block; padding: 10px 20px; background: ${accent}; color: white; border-radius: 8px; text-decoration: none; font-size: 14px; font-weight: 600;">
            ${escapeHtml(params.actionLabel)}
          </a>
        </div>
      </div>
      ${EXPORT_DISCLAIMER_HTML}
    </div>
  `;
}

/** @deprecated Use buildAlertEmailHtml */
export function buildComplianceAlertEmailHtml(params: {
  title: string;
  body: string;
  reviewQueueHref: string;
}): string {
  return buildAlertEmailHtml({
    title: params.title,
    body: params.body,
    actionLabel: "Open Review Queue",
    actionHref: params.reviewQueueHref,
    accentColor: "#a78bfa",
  });
}
