import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";
import { isPrivilegedOrAnonymousJwt } from "../_shared/auth.ts";

const ALLOWED_ORIGIN = Deno.env.get("FRONTEND_URL") ?? (
  (Deno.env.get("SUPABASE_URL") ?? "").includes("localhost") ? "http://localhost:5173" : ""
);

const corsHeaders = {
  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

const DISCLAIMER =
  "Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.";

interface FlankingSample {
  lab_result_id?: string;
  sample_date?: string;
  result_value?: number | null;
  result_text?: string | null;
  unit?: string | null;
  is_non_detect?: boolean;
  analyzed_date?: string | null;
}

interface PacketJson {
  gap_id: string;
  outfall_id: string;
  parameter_id: string;
  scheduled_date: string;
  days_late: number;
  before_sample: FlankingSample | null;
  after_sample: FlankingSample | null;
  defense_note: string;
  outfall_label?: string;
  parameter_label?: string;
  collector_anomalies?: {
    collector_name: string;
    access_issue_count: number;
    access_issue_rate_pct: number;
  }[];
}

async function sha256Hash(data: Uint8Array): Promise<string> {
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hashBuffer))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function sampleLine(sample: FlankingSample | null): string {
  if (!sample?.sample_date) return "No qualifying clean sample in platform data.";
  const value = sample.is_non_detect
    ? "Non-detect"
    : String(sample.result_value ?? sample.result_text ?? "—");
  return `Sample ${sample.sample_date} | Analyzed ${sample.analyzed_date ?? "—"} | Result ${value} ${sample.unit ?? ""}`.trim();
}

async function buildPdf(packet: PacketJson): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const pageWidth = 612;
  const pageHeight = 792;
  const page = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - 60;

  page.drawText("DEFENSIBLE-MISS PACKET (DRAFT)", {
    x: 50,
    y,
    size: 16,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.15),
  });
  y -= 14;
  page.drawText("Counsel review only — not a legal conclusion", {
    x: 50,
    y,
    size: 9,
    font,
    color: rgb(0.5, 0.2, 0.5),
  });
  y -= 24;

  const lines = [
    `Miss date: ${packet.scheduled_date}`,
    `Outfall: ${packet.outfall_label ?? packet.outfall_id}`,
    `Parameter: ${packet.parameter_label ?? packet.parameter_id}`,
    `Days late: ${packet.days_late}`,
    "",
    "Flanking clean sample — BEFORE miss:",
    sampleLine(packet.before_sample),
    "",
    "Flanking clean sample — AFTER miss:",
    sampleLine(packet.after_sample),
    "",
    packet.defense_note,
  ];

  for (const line of lines) {
    page.drawText(line, { x: 50, y, size: 10, font, color: rgb(0.15, 0.15, 0.15), maxWidth: pageWidth - 100 });
    y -= 14;
  }

  if (packet.collector_anomalies?.length) {
    y -= 8;
    page.drawText("Collector access anomalies (top 5):", { x: 50, y, size: 11, font: fontBold, color: rgb(0.15, 0.15, 0.2) });
    y -= 16;
    for (const row of packet.collector_anomalies.slice(0, 5)) {
      page.drawText(
        `${row.collector_name}: ${row.access_issue_count} access issues (${row.access_issue_rate_pct}%)`,
        { x: 50, y, size: 9, font, color: rgb(0.2, 0.2, 0.2) },
      );
      y -= 12;
    }
  }

  page.drawText(DISCLAIMER, {
    x: 50,
    y: 40,
    size: 6,
    font,
    color: rgb(0.5, 0.5, 0.5),
    maxWidth: pageWidth - 100,
  });

  return await pdfDoc.save();
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const serviceClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const token = authHeader.replace("Bearer ", "").trim();
    if (isPrivilegedOrAnonymousJwt(token)) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const { data: { user }, error: authErr } = await serviceClient.auth.getUser(token);
    if (authErr || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { gap_id: gapId } = await req.json();
    if (!gapId) {
      return new Response(JSON.stringify({ error: "gap_id is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: profile } = await serviceClient
      .from("user_profiles")
      .select("organization_id")
      .eq("id", user.id)
      .single();

    const orgId = profile?.organization_id;
    if (!orgId) {
      return new Response(JSON.stringify({ error: "No organization" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: packetRaw, error: rpcErr } = await serviceClient.rpc(
      "get_flanking_samples_for_gap",
      { p_gap_id: gapId },
    );

    if (rpcErr || !packetRaw) {
      return new Response(JSON.stringify({ error: rpcErr?.message ?? "Packet generation failed" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: gapRow } = await serviceClient
      .from("sampling_gap_records")
      .select(`
        id,
        outfalls ( outfall_number, description ),
        parameters ( short_name, name )
      `)
      .eq("id", gapId)
      .eq("organization_id", orgId)
      .single();

    const { data: anomalies } = await serviceClient.rpc("get_collector_access_anomalies", {
      p_org_id: orgId,
      p_lookback_days: 365,
    });

    const packet: PacketJson = {
      ...(packetRaw as PacketJson),
      outfall_label: (gapRow?.outfalls as { outfall_number?: string })?.outfall_number ??
        (gapRow?.outfalls as { description?: string })?.description,
      parameter_label: (gapRow?.parameters as { short_name?: string })?.short_name ??
        (gapRow?.parameters as { name?: string })?.name,
      collector_anomalies: (anomalies ?? []).slice(0, 10),
    };

    const pdfBytes = await buildPdf(packet);
    const pdfData = new Uint8Array(pdfBytes);
    const docHash = await sha256Hash(pdfData);
    const fileName = `defensible_miss_${gapId}_${Date.now()}.pdf`;
    const storagePath = `${orgId}/${fileName}`;

    const { error: uploadErr } = await serviceClient.storage
      .from("defensible-miss-packets")
      .upload(storagePath, pdfData, { contentType: "application/pdf", upsert: false });

    if (uploadErr) {
      console.error("[defensible-miss-pdf] upload failed:", uploadErr.message);
      return new Response(JSON.stringify({ error: uploadErr.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: storedRow, error: insertErr } = await serviceClient
      .from("defensible_miss_packets")
      .insert({
        organization_id: orgId,
        gap_id: gapId,
        generated_by: user.id,
        format: "pdf",
        storage_path: storagePath,
        file_name: fileName,
        sha256_hash: docHash,
        packet_json: packet,
      })
      .select("id, file_name, storage_path, sha256_hash, created_at")
      .single();

    if (insertErr) {
      console.error("[defensible-miss-pdf] insert failed:", insertErr.message);
    }

    const { data: signed } = await serviceClient.storage
      .from("defensible-miss-packets")
      .createSignedUrl(storagePath, 3600);

    await serviceClient.from("audit_log").insert({
      user_id: user.id,
      organization_id: orgId,
      action: "defensible_miss_packet_pdf_stored",
      module: "environmental_compliance",
      table_name: "defensible_miss_packets",
      record_id: storedRow?.id ?? gapId,
      new_values: {
        gap_id: gapId,
        storage_path: storagePath,
        sha256_hash: docHash,
        file_name: fileName,
      },
      description: "Defensible-miss PDF generated and stored (DRAFT — counsel review)",
    });

    return new Response(
      JSON.stringify({
        packet_id: storedRow?.id,
        file_name: fileName,
        storage_path: storagePath,
        sha256_hash: docHash,
        signed_url: signed?.signedUrl ?? null,
        created_at: storedRow?.created_at,
      }),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      },
    );
  } catch (err) {
    console.error("[defensible-miss-pdf]", err);
    return new Response(JSON.stringify({ error: "Internal server error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
