import { useState, useEffect, useCallback } from 'react';
import { useParams, Link } from 'react-router-dom';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { useAuditChecklists } from '@/hooks/useAuditChecklists';
import { useAuditLog } from '@/hooks/useAuditLog';
import {
  ArrowLeft,
  CheckCircle2,
  Circle,
  Clock,
  XCircle,
  MinusCircle,
  Plus,
  Download,
} from 'lucide-react';
import { clsx } from 'clsx';
import type { AuditChecklistItem, ChecklistItemStatus } from '@/types/database';

const ITEM_STATUS_ICONS: Record<ChecklistItemStatus, typeof Circle> = {
  pending: Circle,
  in_progress: Clock,
  complete: CheckCircle2,
  na: MinusCircle,
  blocked: XCircle,
};

const ITEM_STATUS_COLORS: Record<ChecklistItemStatus, string> = {
  pending: 'text-gray-400',
  in_progress: 'text-cyan-400',
  complete: 'text-emerald-400',
  na: 'text-gray-500',
  blocked: 'text-red-400',
};

const NEXT_ITEM_STATUS: ChecklistItemStatus[] = ['pending', 'in_progress', 'complete', 'na', 'blocked'];

const DISCLAIMER = 'Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.';

export function AuditChecklistDetailPage() {
  const { id } = useParams<{ id: string }>();
  const {
    checklists,
    loading,
    fetchItems,
    updateItemStatus,
    updateItemEvidence,
    addItem,
    deleteItem,
    updateChecklistStatus,
  } = useAuditChecklists();
  const { log } = useAuditLog();

  const [items, setItems] = useState<AuditChecklistItem[]>([]);
  const [showAddItem, setShowAddItem] = useState(false);
  const [newCategory, setNewCategory] = useState('General');
  const [newItemText, setNewItemText] = useState('');
  const [editingEvidence, setEditingEvidence] = useState<string | null>(null);
  const [evidenceNotes, setEvidenceNotes] = useState('');

  const checklist = checklists.find((c) => c.id === id);

  const loadItems = useCallback(async () => {
    if (!id) return;
    const data = await fetchItems(id);
    setItems(data);
  }, [id, fetchItems]);

  useEffect(() => {
    loadItems();
  }, [loadItems]);

  const progress = checklist && checklist.total_items > 0
    ? Math.round((checklist.completed_items / checklist.total_items) * 100)
    : 0;

  // Group items by category
  const categories = items.reduce<Record<string, AuditChecklistItem[]>>((acc, item) => {
    const cat = item.category || 'General';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(item);
    return acc;
  }, {});

  const handleStatusToggle = async (item: AuditChecklistItem) => {
    const currentIdx = NEXT_ITEM_STATUS.indexOf(item.status);
    const nextStatus = NEXT_ITEM_STATUS[(currentIdx + 1) % NEXT_ITEM_STATUS.length]!;
    await updateItemStatus(item.id, nextStatus);
    loadItems();
  };

  const handleAddItem = async () => {
    if (!id || !newItemText.trim()) return;
    await addItem(id, { category: newCategory, item_text: newItemText.trim() });
    setNewItemText('');
    setShowAddItem(false);
    loadItems();
  };

  const handleSaveEvidence = async (itemId: string) => {
    await updateItemEvidence(itemId, { evidence_notes: evidenceNotes });
    setEditingEvidence(null);
    setEvidenceNotes('');
    loadItems();
  };

  const handleExport = () => {
    if (!checklist) return;
    const headers = ['Category', 'Item', 'Status', 'Evidence Notes', 'Completed At'];
    const rows = items.map((item) => [
      item.category,
      item.item_text,
      item.status,
      item.evidence_notes ?? '',
      item.completed_at ?? '',
    ]);
    const csv = [headers, ...rows].map((r) => r.map((c) => `"${c}"`).join(',')).join('\n') + `\n\n"${DISCLAIMER}"`;
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `checklist_${checklist.title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    log('audit_checklist_exported', { checklist_id: id }, { module: 'audit', tableName: 'audit_checklists' });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="animate-spin h-8 w-8 border-2 border-indigo-400 border-t-transparent rounded-full" />
      </div>
    );
  }

  if (!checklist) {
    return (
      <div className="text-center py-12">
        <p className="text-text-secondary">Checklist not found</p>
        <Link to="/audit/checklists" className="text-indigo-400 hover:underline mt-2 inline-block">
          Back to Checklists
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Link
          to="/audit/checklists"
          className="p-2 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10"
        >
          <ArrowLeft className="w-4 h-4 text-text-secondary" />
        </Link>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-white">{checklist.title}</h1>
          <div className="flex items-center gap-3 mt-1 text-sm text-text-secondary">
            <span>{checklist.audit_type.replace(/_/g, ' ')}</span>
            {checklist.target_date && <span>Target: {checklist.target_date}</span>}
            <span>{checklist.completed_items}/{checklist.total_items} complete</span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-3 py-2 text-sm bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 text-text-secondary"
          >
            <Download className="w-4 h-4" />
            Export
          </button>
          {checklist.status !== 'complete' && (
            <button
              onClick={() => updateChecklistStatus(checklist.id, 'complete')}
              disabled={progress < 100}
              className="px-4 py-2 text-sm font-medium bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 rounded-lg hover:bg-emerald-500/30 disabled:opacity-40"
              title={progress < 100 ? 'Complete all items first' : 'Mark as complete'}
            >
              Mark Complete
            </button>
          )}
        </div>
      </div>

      {/* Progress Bar */}
      <SpotlightCard className="p-4">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm text-text-secondary">Progress</span>
          <span className="text-sm font-bold text-white">{progress}%</span>
        </div>
        <div className="w-full h-2 bg-white/10 rounded-full overflow-hidden">
          <div
            className={clsx(
              'h-full rounded-full transition-all',
              progress === 100 ? 'bg-emerald-500' : progress >= 50 ? 'bg-cyan-500' : 'bg-amber-500',
            )}
            style={{ width: `${progress}%` }}
          />
        </div>
      </SpotlightCard>

      {/* Items by Category */}
      {Object.entries(categories).map(([category, categoryItems]) => (
        <SpotlightCard key={category} className="p-4">
          <h3 className="text-sm font-medium text-text-secondary mb-3">{category}</h3>
          <div className="space-y-1">
            {categoryItems.map((item) => {
              const StatusIcon = ITEM_STATUS_ICONS[item.status];
              return (
                <div key={item.id} className="group">
                  <div className="flex items-start gap-3 py-2 px-2 rounded hover:bg-white/[0.02]">
                    <button
                      onClick={() => handleStatusToggle(item)}
                      className="mt-0.5 flex-shrink-0"
                      title={`Status: ${item.status} (click to cycle)`}
                    >
                      <StatusIcon className={clsx('w-5 h-5', ITEM_STATUS_COLORS[item.status])} />
                    </button>
                    <div className="flex-1 min-w-0">
                      <span className={clsx(
                        'text-sm',
                        item.status === 'complete' ? 'text-text-secondary line-through' : 'text-white',
                      )}>
                        {item.item_text}
                      </span>
                      {item.description && (
                        <p className="text-xs text-text-secondary mt-0.5">{item.description}</p>
                      )}
                      {item.evidence_notes && (
                        <p className="text-xs text-indigo-300 mt-0.5">Evidence: {item.evidence_notes}</p>
                      )}
                      {editingEvidence === item.id && (
                        <div className="flex gap-2 mt-2">
                          <input
                            value={evidenceNotes}
                            onChange={(e) => setEvidenceNotes(e.target.value)}
                            className="flex-1 px-2 py-1 bg-white/5 border border-white/10 rounded text-sm text-white focus:outline-none"
                            placeholder="Evidence notes..."
                            autoFocus
                          />
                          <button
                            onClick={() => handleSaveEvidence(item.id)}
                            className="px-2 py-1 text-xs bg-indigo-500/20 text-indigo-300 rounded"
                          >
                            Save
                          </button>
                          <button
                            onClick={() => setEditingEvidence(null)}
                            className="px-2 py-1 text-xs text-text-secondary"
                          >
                            Cancel
                          </button>
                        </div>
                      )}
                    </div>
                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button
                        onClick={() => {
                          setEditingEvidence(item.id);
                          setEvidenceNotes(item.evidence_notes ?? '');
                        }}
                        className="px-2 py-0.5 text-xs text-text-secondary hover:text-indigo-300"
                      >
                        Evidence
                      </button>
                      <button
                        onClick={() => { deleteItem(item.id); loadItems(); }}
                        className="px-2 py-0.5 text-xs text-text-secondary hover:text-red-400"
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </SpotlightCard>
      ))}

      {/* Add Item */}
      {showAddItem ? (
        <SpotlightCard className="p-4">
          <div className="flex gap-2">
            <input
              value={newCategory}
              onChange={(e) => setNewCategory(e.target.value)}
              className="w-32 px-2 py-1.5 bg-white/5 border border-white/10 rounded text-sm text-white focus:outline-none"
              placeholder="Category"
            />
            <input
              value={newItemText}
              onChange={(e) => setNewItemText(e.target.value)}
              className="flex-1 px-2 py-1.5 bg-white/5 border border-white/10 rounded text-sm text-white focus:outline-none"
              placeholder="Checklist item..."
              onKeyDown={(e) => { if (e.key === 'Enter') handleAddItem(); }}
              autoFocus
            />
            <button
              onClick={handleAddItem}
              disabled={!newItemText.trim()}
              className="px-3 py-1.5 text-xs font-medium bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 rounded hover:bg-indigo-500/30 disabled:opacity-40"
            >
              Add
            </button>
            <button onClick={() => setShowAddItem(false)} className="px-3 py-1.5 text-xs text-text-secondary">
              Cancel
            </button>
          </div>
        </SpotlightCard>
      ) : (
        <button
          onClick={() => setShowAddItem(true)}
          className="flex items-center gap-2 text-sm text-text-secondary hover:text-indigo-300 transition-colors"
        >
          <Plus className="w-4 h-4" />
          Add Item
        </button>
      )}
    </div>
  );
}

export default AuditChecklistDetailPage;
