import { BarChart3, TrendingUp, Clock, CheckCircle2, AlertTriangle, Users, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { cn } from '@/lib/cn';
import { useCorrectiveActions } from '@/hooks/useCorrectiveActions';
import { useCAAnalytics } from '@/hooks/useCAAnalytics';
import { useAuditLog } from '@/hooks/useAuditLog';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { WORKFLOW_STEP_SHORT_LABELS, CA_STATUS_LABELS, CA_PRIORITY_LABELS, SOURCE_TYPE_LABELS } from '@/types/corrective-actions';
import type { WorkflowStep, CAStatus, CAPriority } from '@/types/corrective-actions';

// ─── Color maps ────────────────────────────────────────────────────────
const STATUS_BAR_COLORS: Record<CAStatus, string> = {
  open: 'bg-cyan-400',
  in_progress: 'bg-amber-400',
  completed: 'bg-purple-400',
  verified: 'bg-blue-400',
  closed: 'bg-emerald-400',
};

const PRIORITY_BAR_COLORS: Record<CAPriority, string> = {
  critical: 'bg-red-400',
  high: 'bg-orange-400',
  medium: 'bg-amber-400',
  low: 'bg-emerald-400',
};

export function CAAnalyticsPage() {
  const { allActions, loading } = useCorrectiveActions();
  const { log } = useAuditLog();
  const {
    metrics,
    sourceBreakdown,
    stepBottleneck,
    overdueByAssignee,
    monthlyTrend,
    priorityDistribution,
    statusDistribution,
  } = useCAAnalytics(allActions);

  // CSV export
  function handleExport() {
    const headers = ['Month', 'Opened', 'Closed'];
    const rows = monthlyTrend.map((t) => `${t.month},${t.opened},${t.closed}`);
    const disclaimer = '# Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.';
    const csv = `${disclaimer}\n${headers.join(',')}\n${rows.join('\n')}`;
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ca-analytics-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);

    log('corrective_action_exported', { type: 'analytics_csv' }, {
      module: 'corrective_actions',
      tableName: 'corrective_actions',
    });
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  const maxTrend = Math.max(...monthlyTrend.map((t) => Math.max(t.opened, t.closed)), 1);
  const maxStatus = Math.max(...Object.values(statusDistribution), 1);
  const maxPriority = Math.max(...Object.values(priorityDistribution), 1);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-3">
          <Link
            to="/corrective-actions"
            className="inline-flex items-center gap-1 text-xs text-text-muted hover:text-text-secondary transition-colors"
          >
            <ArrowLeft size={12} />
            Back
          </Link>
          <div className="p-2 rounded-lg bg-cyan-500/10 border border-cyan-500/20">
            <BarChart3 className="h-6 w-6 text-cyan-400" />
          </div>
          <div>
            <h1 className="text-2xl font-semibold text-text-primary">CA Analytics</h1>
            <p className="text-sm text-text-muted">
              Corrective Action performance metrics · {allActions.length} total actions
            </p>
          </div>
        </div>
        <button
          onClick={handleExport}
          className="rounded-lg bg-white/[0.06] border border-white/[0.08] px-4 py-2 text-sm font-medium text-text-secondary hover:bg-white/[0.1] transition-colors"
        >
          Export CSV
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <SpotlightCard className="p-4" spotlightColor="rgba(6, 182, 212, 0.08)">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-cyan-500/10 border border-cyan-500/20">
              <Clock className="h-4 w-4 text-cyan-400" />
            </div>
            <div>
              <div className="text-2xl font-semibold text-cyan-400">{metrics.open}</div>
              <div className="text-[11px] text-text-muted uppercase tracking-wider">Open</div>
            </div>
          </div>
        </SpotlightCard>

        <SpotlightCard className="p-4" spotlightColor="rgba(239, 68, 68, 0.08)">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-red-500/10 border border-red-500/20">
              <AlertTriangle className="h-4 w-4 text-red-400" />
            </div>
            <div>
              <div className="text-2xl font-semibold text-red-400">{metrics.overdue}</div>
              <div className="text-[11px] text-text-muted uppercase tracking-wider">Overdue</div>
            </div>
          </div>
        </SpotlightCard>

        <SpotlightCard className="p-4" spotlightColor="rgba(168, 85, 247, 0.08)">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-purple-500/10 border border-purple-500/20">
              <TrendingUp className="h-4 w-4 text-purple-400" />
            </div>
            <div>
              <div className="text-2xl font-semibold text-purple-400">{metrics.avgDaysToClose}d</div>
              <div className="text-[11px] text-text-muted uppercase tracking-wider">Avg Close</div>
            </div>
          </div>
        </SpotlightCard>

        <SpotlightCard className="p-4" spotlightColor="rgba(16, 185, 129, 0.08)">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
              <CheckCircle2 className="h-4 w-4 text-emerald-400" />
            </div>
            <div>
              <div className="text-2xl font-semibold text-emerald-400">{metrics.onTimeClosureRate}%</div>
              <div className="text-[11px] text-text-muted uppercase tracking-wider">On Time</div>
            </div>
          </div>
        </SpotlightCard>
      </div>

      {/* Two column layout */}
      <div className="grid gap-4 grid-cols-1 lg:grid-cols-2">
        {/* Monthly Trend */}
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4">
          <h3 className="text-sm font-semibold text-text-primary mb-3">Monthly Trend (12 months)</h3>
          <div className="space-y-1.5">
            {monthlyTrend.map((t) => (
              <div key={t.month} className="flex items-center gap-2 text-xs">
                <span className="w-16 text-text-muted font-mono">{t.month}</span>
                <div className="flex-1 flex items-center gap-1">
                  <div
                    className="h-3 rounded bg-cyan-400/60"
                    style={{ width: `${(t.opened / maxTrend) * 100}%`, minWidth: t.opened > 0 ? '4px' : '0' }}
                    title={`${t.opened} opened`}
                  />
                  <div
                    className="h-3 rounded bg-emerald-400/60"
                    style={{ width: `${(t.closed / maxTrend) * 100}%`, minWidth: t.closed > 0 ? '4px' : '0' }}
                    title={`${t.closed} closed`}
                  />
                </div>
                <span className="w-12 text-right text-text-muted">
                  <span className="text-cyan-400">{t.opened}</span>
                  /
                  <span className="text-emerald-400">{t.closed}</span>
                </span>
              </div>
            ))}
          </div>
          <div className="flex items-center gap-4 mt-2 text-[10px] text-text-muted">
            <span className="flex items-center gap-1"><span className="inline-block w-2 h-2 rounded bg-cyan-400/60" /> Opened</span>
            <span className="flex items-center gap-1"><span className="inline-block w-2 h-2 rounded bg-emerald-400/60" /> Closed</span>
          </div>
        </div>

        {/* Source Breakdown */}
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4">
          <h3 className="text-sm font-semibold text-text-primary mb-3">Source Breakdown</h3>
          {sourceBreakdown.length === 0 ? (
            <p className="text-xs text-text-muted py-4 text-center">No data</p>
          ) : (
            <div className="space-y-2">
              {sourceBreakdown.map((s) => (
                <div key={s.source_type} className="flex items-center gap-3">
                  <span className="w-32 text-xs text-text-muted truncate">
                    {SOURCE_TYPE_LABELS[s.source_type] ?? s.source_type}
                  </span>
                  <div className="flex-1 bg-white/[0.04] rounded-full h-4 overflow-hidden">
                    <div
                      className="h-full bg-cyan-400/40 rounded-full"
                      style={{ width: `${(s.count / (sourceBreakdown[0]?.count ?? 1)) * 100}%` }}
                    />
                  </div>
                  <span className="text-xs font-mono text-text-secondary w-8 text-right">{s.count}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Status Distribution */}
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4">
          <h3 className="text-sm font-semibold text-text-primary mb-3">Status Distribution</h3>
          <div className="space-y-2">
            {(Object.entries(statusDistribution) as [CAStatus, number][]).map(([status, count]) => (
              <div key={status} className="flex items-center gap-3">
                <span className="w-24 text-xs text-text-muted">{CA_STATUS_LABELS[status]}</span>
                <div className="flex-1 bg-white/[0.04] rounded-full h-4 overflow-hidden">
                  <div
                    className={cn('h-full rounded-full', STATUS_BAR_COLORS[status])}
                    style={{ width: `${(count / maxStatus) * 100}%` }}
                  />
                </div>
                <span className="text-xs font-mono text-text-secondary w-8 text-right">{count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Priority Distribution (open only) */}
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4">
          <h3 className="text-sm font-semibold text-text-primary mb-3">Open by Priority</h3>
          <div className="space-y-2">
            {(Object.entries(priorityDistribution) as [CAPriority, number][]).map(([prio, count]) => (
              <div key={prio} className="flex items-center gap-3">
                <span className="w-20 text-xs text-text-muted">{CA_PRIORITY_LABELS[prio]}</span>
                <div className="flex-1 bg-white/[0.04] rounded-full h-4 overflow-hidden">
                  <div
                    className={cn('h-full rounded-full', PRIORITY_BAR_COLORS[prio])}
                    style={{ width: `${(count / maxPriority) * 100}%` }}
                  />
                </div>
                <span className="text-xs font-mono text-text-secondary w-8 text-right">{count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Workflow Step Bottleneck */}
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4">
          <h3 className="text-sm font-semibold text-text-primary mb-3">Workflow Bottleneck (Open CAs)</h3>
          {stepBottleneck.length === 0 ? (
            <p className="text-xs text-text-muted py-4 text-center">No open CAs</p>
          ) : (
            <div className="space-y-2">
              {stepBottleneck.map((s) => (
                <div key={s.step} className="flex items-center gap-3">
                  <span className="w-28 text-xs text-text-muted truncate">
                    {WORKFLOW_STEP_SHORT_LABELS[s.step as WorkflowStep] ?? s.step}
                  </span>
                  <div className="flex-1 bg-white/[0.04] rounded-full h-4 overflow-hidden">
                    <div
                      className="h-full bg-amber-400/40 rounded-full"
                      style={{ width: `${(s.count / (stepBottleneck[0]?.count ?? 1)) * 100}%` }}
                    />
                  </div>
                  <span className="text-xs text-text-secondary w-20 text-right">
                    <span className="font-mono">{s.count}</span>
                    <span className="text-text-muted ml-1">({s.avgDaysInStep}d avg)</span>
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Overdue by Assignee */}
        <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4">
          <div className="flex items-center gap-2 mb-3">
            <Users size={14} className="text-red-400" />
            <h3 className="text-sm font-semibold text-text-primary">Overdue by Assignee</h3>
          </div>
          {overdueByAssignee.length === 0 ? (
            <p className="text-xs text-emerald-400 py-4 text-center">No overdue assignments</p>
          ) : (
            <div className="divide-y divide-white/[0.04]">
              {overdueByAssignee.map((a) => (
                <div key={a.assignee_id} className="flex items-center justify-between py-2">
                  <span className="text-xs text-text-secondary">{a.assignee_name}</span>
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-mono text-red-400">{a.overdue_count} overdue</span>
                    <span className="text-xs text-text-muted">/ {a.total_assigned} total</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* 30-day summary */}
      <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4">
        <h3 className="text-sm font-semibold text-text-primary mb-2">Last 30 Days</h3>
        <div className="flex gap-8 text-sm">
          <span className="text-text-muted">
            Opened: <span className="text-cyan-400 font-mono">{metrics.openedLast30}</span>
          </span>
          <span className="text-text-muted">
            Closed: <span className="text-emerald-400 font-mono">{metrics.closedLast30}</span>
          </span>
          <span className="text-text-muted">
            Net: <span className={cn(
              'font-mono',
              metrics.openedLast30 > metrics.closedLast30 ? 'text-red-400' : 'text-emerald-400',
            )}>
              {metrics.openedLast30 - metrics.closedLast30 > 0 ? '+' : ''}
              {metrics.openedLast30 - metrics.closedLast30}
            </span>
          </span>
        </div>
      </div>
    </div>
  );
}

export default CAAnalyticsPage;
