import { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { useComplianceSnapshots, evaluateKPI } from '@/hooks/useComplianceSnapshots';
import { useStatutoryAlertAcks } from '@/hooks/useStatutoryAlertAcks';
import { useAuditLog } from '@/hooks/useAuditLog';
import {
  BarChart3,
  RefreshCw,
  Download,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  CheckCircle2,
  ShieldAlert,
  ClipboardList,
  Activity,
  Gauge,
  MapPin,
} from 'lucide-react';
import { clsx } from 'clsx';
const KPI_STATUS_COLORS = {
  green: 'text-qo-sage-text bg-qo-sage/10 border-qo-sage/30',
  yellow: 'text-qo-ochre-text bg-qo-ochre/10 border-qo-ochre/30',
  red: 'text-qo-risk bg-qo-risk/10 border-qo-risk/30',
  unknown: 'text-text-muted bg-black/[0.04] border-black/[0.08]',
};

const KPI_STATUS_DOT = {
  green: 'bg-qo-sage',
  yellow: 'bg-qo-ochre',
  red: 'bg-qo-risk',
  unknown: 'bg-text-muted',
};

const TREND_DAYS_OPTIONS = [30, 60, 90] as const;

const DISCLAIMER = 'Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.';

export function ComplianceDashboardPage() {
  const {
    latestSnapshot,
    trend,
    kpiTargets,
    loading,
    generating,
    generateSnapshot,
    getKPIValue,
    fetchTrend,
  } = useComplianceSnapshots();
  const statutoryAcks = useStatutoryAlertAcks();
  const { log } = useAuditLog();
  const [trendDays, setTrendDays] = useState<30 | 60 | 90>(30);

  const handleTrendChange = async (days: 30 | 60 | 90) => {
    setTrendDays(days);
    await fetchTrend(days);
  };

  // Score gauge color
  const scoreColor = useMemo(() => {
    if (!latestSnapshot) return 'text-text-muted';
    if (latestSnapshot.compliance_score >= 90) return 'text-qo-sage-text';
    if (latestSnapshot.compliance_score >= 80) return 'text-qo-ochre-text';
    return 'text-qo-risk';
  }, [latestSnapshot]);

  // Trend direction
  const trendDirection = useMemo(() => {
    if (trend.length < 2) return null;
    const first = trend[0]!.compliance_score;
    const last = trend[trend.length - 1]!.compliance_score;
    return last >= first ? 'up' : 'down';
  }, [trend]);

  // State breakdown from latest snapshot
  const stateBreakdown = latestSnapshot?.state_breakdown ?? [];

  const handleExport = () => {
    if (!latestSnapshot) return;
    const lines = [
      'SCC Compliance Dashboard Export',
      `Generated: ${new Date().toISOString()}`,
      `Snapshot Date: ${latestSnapshot.snapshot_date}`,
      '',
      'Metric,Value',
      `Compliance Score,${latestSnapshot.compliance_score}`,
      `Sampling Compliance %,${latestSnapshot.sampling_compliance_pct}`,
      `Exceedance Rate %,${latestSnapshot.exceedance_rate_pct}`,
      `Active Permits,${latestSnapshot.active_permits}`,
      `Active Outfalls,${latestSnapshot.active_outfalls}`,
      `Open Violations,${latestSnapshot.open_violations}`,
      `Critical Violations,${latestSnapshot.critical_violations}`,
      `Open CAs,${latestSnapshot.open_corrective_actions}`,
      `Overdue CAs,${latestSnapshot.overdue_corrective_actions}`,
      `Avg CA Closure Days,${latestSnapshot.avg_ca_closure_days ?? 'N/A'}`,
      `Open Work Orders,${latestSnapshot.open_work_orders}`,
      `Overdue Work Orders,${latestSnapshot.overdue_work_orders}`,
      `DMR Submission Rate %,${latestSnapshot.dmr_submission_rate_pct}`,
      `Open Incidents,${latestSnapshot.open_incidents}`,
      `Total Penalties,$${latestSnapshot.total_penalties}`,
      '',
      `"${DISCLAIMER}"`,
    ];
    const csv = lines.join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance_dashboard_${latestSnapshot.snapshot_date}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    log('compliance_dashboard_exported', { date: latestSnapshot.snapshot_date }, {
      module: 'compliance_dashboard',
      tableName: 'compliance_snapshots',
    });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="animate-spin h-8 w-8 border-2 border-qo-accent border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-qo-accent/20">
            <BarChart3 className="w-6 h-6 text-qo-accent" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-text-primary">Compliance Dashboard</h1>
            <p className="text-sm text-text-secondary">
              {latestSnapshot
                ? `Snapshot: ${latestSnapshot.snapshot_date}`
                : 'No snapshots generated yet'}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleExport}
            disabled={!latestSnapshot}
            className="flex items-center gap-2 px-3 py-2 text-sm bg-qo-nested border border-black/[0.08] rounded-lg hover:bg-black/[0.06] text-text-secondary disabled:opacity-40"
          >
            <Download className="w-4 h-4" />
            Export
          </button>
          <button
            onClick={() => generateSnapshot()}
            disabled={generating}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium bg-qo-accent/20 text-qo-accent border border-qo-accent/30 rounded-lg hover:bg-qo-accent/30 disabled:opacity-40"
          >
            <RefreshCw className={clsx('w-4 h-4', generating && 'animate-spin')} />
            {generating ? 'Generating...' : 'Generate Snapshot'}
          </button>
        </div>
      </div>

      {!statutoryAcks.loading && statutoryAcks.unacknowledgedCount > 0 && (
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-qo-ochre/30 bg-qo-ochre/10 px-4 py-3">
          <p className="text-sm text-qo-ochre-text">
            <ShieldAlert className="inline w-4 h-4 mr-1.5 align-text-bottom" />
            {statutoryAcks.unacknowledgedCount} statutory alert
            {statutoryAcks.unacknowledgedCount !== 1 ? 's' : ''} awaiting acknowledgment
          </p>
          <div className="flex flex-wrap gap-3 text-xs font-medium">
            <Link to="/compliance/missed-at-risk" className="text-qo-accent hover:underline">
              Sampling gaps
            </Link>
            <Link to="/compliance/late-incomplete-edd" className="text-qo-accent hover:underline">
              ¶49 EDD
            </Link>
            <Link to="/compliance/external-data" className="text-qo-accent hover:underline">
              MSHA
            </Link>
            <Link to="/monitoring" className="text-qo-accent hover:underline">
              Exceedances
            </Link>
          </div>
        </div>
      )}

      {!latestSnapshot ? (
        <SpotlightCard className="p-12 text-center">
          <Gauge className="w-10 h-10 text-text-secondary mx-auto mb-3" />
          <h3 className="text-lg font-semibold text-text-primary mb-2">No Compliance Data Yet</h3>
          <p className="text-text-secondary mb-4">
            Generate your first compliance snapshot to see KPIs and trends.
          </p>
          <button
            onClick={() => generateSnapshot()}
            disabled={generating}
            className="px-4 py-2 text-sm font-medium bg-qo-accent/20 text-qo-accent border border-qo-accent/30 rounded-lg hover:bg-qo-accent/30"
          >
            Generate Now
          </button>
        </SpotlightCard>
      ) : (
        <>
          {/* Compliance Score + Trend Direction */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <SpotlightCard className="p-6 md:col-span-1 flex flex-col items-center justify-center">
              <Gauge className={clsx('w-8 h-8 mb-2', scoreColor)} />
              <div className={clsx('text-4xl font-bold', scoreColor)}>
                {latestSnapshot.compliance_score.toFixed(1)}
              </div>
              <div className="text-sm text-text-secondary mt-1">Compliance Score</div>
              {trendDirection && (
                <div className={clsx(
                  'flex items-center gap-1 text-xs mt-2',
                  trendDirection === 'up' ? 'text-qo-sage-text' : 'text-qo-risk',
                )}>
                  {trendDirection === 'up' ? (
                    <TrendingUp className="w-3 h-3" />
                  ) : (
                    <TrendingDown className="w-3 h-3" />
                  )}
                  {trendDirection === 'up' ? 'Improving' : 'Declining'} over {trendDays}d
                </div>
              )}
            </SpotlightCard>

            {/* Quick Stats */}
            <div className="md:col-span-3 grid grid-cols-2 sm:grid-cols-4 gap-3">
              {[
                {
                  label: 'Sampling Compliance',
                  value: `${latestSnapshot.sampling_compliance_pct}%`,
                  icon: Activity,
                  color: latestSnapshot.sampling_compliance_pct >= 95 ? 'text-qo-sage-text' : latestSnapshot.sampling_compliance_pct >= 85 ? 'text-qo-ochre-text' : 'text-qo-risk',
                },
                {
                  label: 'Exceedance Rate',
                  value: `${latestSnapshot.exceedance_rate_pct}%`,
                  icon: AlertTriangle,
                  color: latestSnapshot.exceedance_rate_pct <= 2 ? 'text-qo-sage-text' : latestSnapshot.exceedance_rate_pct <= 5 ? 'text-qo-ochre-text' : 'text-qo-risk',
                },
                {
                  label: 'Open Violations',
                  value: latestSnapshot.open_violations.toString(),
                  icon: ShieldAlert,
                  color: latestSnapshot.open_violations === 0 ? 'text-qo-sage-text' : latestSnapshot.open_violations <= 3 ? 'text-qo-ochre-text' : 'text-qo-risk',
                },
                {
                  label: 'DMR Rate',
                  value: `${latestSnapshot.dmr_submission_rate_pct}%`,
                  icon: CheckCircle2,
                  color: latestSnapshot.dmr_submission_rate_pct >= 100 ? 'text-qo-sage-text' : latestSnapshot.dmr_submission_rate_pct >= 90 ? 'text-qo-ochre-text' : 'text-qo-risk',
                },
                {
                  label: 'Open CAs',
                  value: latestSnapshot.open_corrective_actions.toString(),
                  sub: `${latestSnapshot.overdue_corrective_actions} overdue`,
                  icon: ClipboardList,
                  color: latestSnapshot.overdue_corrective_actions === 0 ? 'text-qo-sage-text' : 'text-qo-ochre-text',
                },
                {
                  label: 'Open Work Orders',
                  value: latestSnapshot.open_work_orders.toString(),
                  sub: `${latestSnapshot.overdue_work_orders} overdue`,
                  icon: ClipboardList,
                  color: latestSnapshot.overdue_work_orders === 0 ? 'text-qo-sage-text' : 'text-qo-ochre-text',
                },
                {
                  label: 'Active Permits',
                  value: latestSnapshot.active_permits.toString(),
                  sub: `${latestSnapshot.active_outfalls} outfalls`,
                  icon: Activity,
                  color: 'text-qo-accent',
                },
                {
                  label: 'Total Penalties',
                  value: `$${latestSnapshot.total_penalties.toLocaleString()}`,
                  icon: AlertTriangle,
                  color: latestSnapshot.total_penalties > 0 ? 'text-qo-risk' : 'text-qo-sage-text',
                },
              ].map(({ label, value, sub, icon: Icon, color }) => (
                <SpotlightCard key={label} className="p-3">
                  <Icon className={clsx('w-4 h-4 mb-1', color)} />
                  <div className={clsx('text-xl font-bold', color)}>{value}</div>
                  <div className="text-xs text-text-secondary">{label}</div>
                  {sub && <div className="text-xs text-text-secondary mt-0.5">{sub}</div>}
                </SpotlightCard>
              ))}
            </div>
          </div>

          {/* KPI Targets */}
          <SpotlightCard className="p-4">
            <h3 className="text-sm font-medium text-text-secondary mb-4">KPI Targets</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {kpiTargets.map((kpi) => {
                const value = getKPIValue(kpi.kpi_key);
                const status = value != null ? evaluateKPI(value, kpi) : 'unknown';
                return (
                  <div
                    key={kpi.id}
                    className={clsx(
                      'p-3 rounded-lg border',
                      KPI_STATUS_COLORS[status],
                    )}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-sm font-medium">{kpi.display_name}</span>
                      <div className={clsx('w-2.5 h-2.5 rounded-full', KPI_STATUS_DOT[status])} />
                    </div>
                    <div className="text-lg font-bold">
                      {value != null ? `${value}${kpi.unit === '%' ? '%' : kpi.unit === 'days' ? 'd' : ''}` : '—'}
                    </div>
                    <div className="text-xs opacity-70">
                      Target: {kpi.direction === 'below' ? '≤' : '≥'} {kpi.target_value}{kpi.unit === '%' ? '%' : ''}
                    </div>
                  </div>
                );
              })}
            </div>
          </SpotlightCard>

          {/* Trend Chart */}
          <SpotlightCard className="p-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-medium text-text-secondary">Compliance Trend</h3>
              <div className="flex items-center gap-1">
                {TREND_DAYS_OPTIONS.map((d) => (
                  <button
                    key={d}
                    onClick={() => handleTrendChange(d)}
                    className={clsx(
                      'px-2 py-1 text-xs rounded',
                      trendDays === d
                        ? 'bg-qo-accent/20 text-qo-accent'
                        : 'text-text-secondary hover:text-text-primary',
                    )}
                  >
                    {d}d
                  </button>
                ))}
              </div>
            </div>

            {trend.length === 0 ? (
              <p className="text-sm text-text-secondary text-center py-8">
                Generate daily snapshots to build trend data
              </p>
            ) : (
              <div className="space-y-1">
                {/* Simple bar chart representation */}
                <div className="flex items-end gap-1 h-32">
                  {trend.map((point, i) => {
                    const height = Math.max(4, (point.compliance_score / 100) * 128);
                    const barColor = point.compliance_score >= 90
                      ? 'bg-emerald-500/60'
                      : point.compliance_score >= 80
                        ? 'bg-amber-500/60'
                        : 'bg-red-500/60';
                    return (
                      <div
                        key={i}
                        className="flex-1 group relative"
                        title={`${point.snapshot_date}: ${point.compliance_score.toFixed(1)}`}
                      >
                        <div
                          className={clsx('rounded-t transition-all hover:opacity-100 opacity-80', barColor)}
                          style={{ height: `${height}px` }}
                        />
                      </div>
                    );
                  })}
                </div>
                <div className="flex justify-between text-xs text-text-secondary">
                  <span>{trend[0]?.snapshot_date}</span>
                  <span>{trend[trend.length - 1]?.snapshot_date}</span>
                </div>
              </div>
            )}
          </SpotlightCard>

          {/* State Breakdown */}
          {stateBreakdown.length > 0 && (
            <SpotlightCard className="p-4">
              <div className="flex items-center gap-2 mb-4">
                <MapPin className="w-4 h-4 text-qo-accent" />
                <h3 className="text-sm font-medium text-text-secondary">State Breakdown</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-text-secondary border-b border-white/5">
                      <th className="pb-2 pr-4">State</th>
                      <th className="pb-2 pr-4 text-right">Permits</th>
                      <th className="pb-2 pr-4 text-right">Outfalls</th>
                      <th className="pb-2 pr-4 text-right">Exceedances</th>
                      <th className="pb-2 text-right">Violations</th>
                    </tr>
                  </thead>
                  <tbody>
                    {stateBreakdown.map((s) => (
                      <tr key={s.state} className="border-b border-white/[0.03]">
                        <td className="py-2 pr-4 text-text-primary font-medium">{s.state}</td>
                        <td className="py-2 pr-4 text-right text-text-primary">{s.permits}</td>
                        <td className="py-2 pr-4 text-right text-text-primary">{s.outfalls}</td>
                        <td className="py-2 pr-4 text-right">
                          <span className={clsx(
                            s.exceedances > 0 ? 'text-qo-risk' : 'text-qo-sage-text',
                          )}>
                            {s.exceedances}
                          </span>
                        </td>
                        <td className="py-2 text-right">
                          <span className={clsx(
                            s.violations > 0 ? 'text-qo-risk' : 'text-qo-sage-text',
                          )}>
                            {s.violations}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </SpotlightCard>
          )}

          {/* Open Items Summary */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <SpotlightCard className="p-4">
              <h3 className="text-sm font-medium text-text-secondary mb-3">Overdue Items</h3>
              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-text-primary">Corrective Actions</span>
                  <span className={clsx(
                    'text-sm font-bold',
                    latestSnapshot.overdue_corrective_actions > 0 ? 'text-qo-risk' : 'text-qo-sage-text',
                  )}>
                    {latestSnapshot.overdue_corrective_actions}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-text-primary">Work Orders</span>
                  <span className={clsx(
                    'text-sm font-bold',
                    latestSnapshot.overdue_work_orders > 0 ? 'text-qo-risk' : 'text-qo-sage-text',
                  )}>
                    {latestSnapshot.overdue_work_orders}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-text-primary">Critical Violations</span>
                  <span className={clsx(
                    'text-sm font-bold',
                    latestSnapshot.critical_violations > 0 ? 'text-qo-risk' : 'text-qo-sage-text',
                  )}>
                    {latestSnapshot.critical_violations}
                  </span>
                </div>
              </div>
            </SpotlightCard>

            <SpotlightCard className="p-4">
              <h3 className="text-sm font-medium text-text-secondary mb-3">Sampling & Reporting</h3>
              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-text-primary">Samples Due (30d)</span>
                  <span className="text-sm font-bold text-text-primary">{latestSnapshot.sampling_events_due}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-text-primary">Samples Completed</span>
                  <span className="text-sm font-bold text-qo-sage-text">{latestSnapshot.sampling_events_completed}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-text-primary">DMRs Due (Quarter)</span>
                  <span className="text-sm font-bold text-text-primary">{latestSnapshot.dmr_submissions_due}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-text-primary">DMRs Submitted</span>
                  <span className="text-sm font-bold text-qo-sage-text">{latestSnapshot.dmr_submissions_completed}</span>
                </div>
              </div>
            </SpotlightCard>
          </div>
        </>
      )}
    </div>
  );
}

export default ComplianceDashboardPage;
