import { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { useComplianceViolations } from '@/hooks/useComplianceViolations';
import { useAuditLog } from '@/hooks/useAuditLog';
import {
  ShieldAlert,
  Plus,
  Download,
  AlertTriangle,
  Search as SearchIcon,
  Filter,
  DollarSign,
} from 'lucide-react';
import { clsx } from 'clsx';
import type { ViolationType, ViolationSeverity, ViolationStatus } from '@/types/database';

const STATUS_LABELS: Record<ViolationStatus, string> = {
  open: 'Open',
  under_investigation: 'Under Investigation',
  reported: 'Reported',
  resolved: 'Resolved',
  closed: 'Closed',
};

const STATUS_COLORS: Record<ViolationStatus, string> = {
  open: 'bg-red-500/20 text-red-300 border-red-500/30',
  under_investigation: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
  reported: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  resolved: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  closed: 'bg-gray-500/20 text-gray-400 border-gray-500/30',
};

const SEVERITY_COLORS: Record<ViolationSeverity, string> = {
  minor: 'bg-gray-500/20 text-gray-300',
  moderate: 'bg-amber-500/20 text-amber-300',
  major: 'bg-orange-500/20 text-orange-300',
  critical: 'bg-red-500/20 text-red-300',
};

const TYPE_LABELS: Record<ViolationType, string> = {
  permit_exceedance: 'Permit Exceedance',
  reporting_failure: 'Reporting Failure',
  monitoring_failure: 'Monitoring Failure',
  discharge_violation: 'Discharge Violation',
  bmp_failure: 'BMP Failure',
  consent_decree_violation: 'Consent Decree Violation',
  spill: 'Spill',
  unauthorized_discharge: 'Unauthorized Discharge',
  recordkeeping: 'Recordkeeping',
  other: 'Other',
};

const DISCLAIMER = 'Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.';

export function ComplianceViolationsPage() {
  const { violations, loading, statusCounts, createViolation } = useComplianceViolations();
  const { log } = useAuditLog();
  const [statusFilter, setStatusFilter] = useState<ViolationStatus | 'all'>('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [showCreate, setShowCreate] = useState(false);

  // Create form
  const [violationType, setViolationType] = useState<ViolationType>('permit_exceedance');
  const [severity, setSeverity] = useState<ViolationSeverity>('minor');
  const [violationDate, setViolationDate] = useState(new Date().toISOString().split('T')[0]);
  const [description, setDescription] = useState('');

  const filtered = useMemo(() => {
    let result = violations;
    if (statusFilter !== 'all') {
      result = result.filter((v) => v.status === statusFilter);
    }
    if (searchTerm) {
      const lower = searchTerm.toLowerCase();
      result = result.filter(
        (v) =>
          v.description?.toLowerCase().includes(lower) ||
          v.site_name?.toLowerCase().includes(lower) ||
          v.permit_number?.toLowerCase().includes(lower) ||
          v.parameter_name?.toLowerCase().includes(lower),
      );
    }
    return result;
  }, [violations, statusFilter, searchTerm]);

  const handleCreate = async () => {
    const result = await createViolation({
      violation_type: violationType,
      severity,
      violation_date: violationDate,
      description: description.trim() || null,
    });
    if (result) {
      setDescription('');
      setShowCreate(false);
    }
  };

  const handleExport = () => {
    const headers = ['Type', 'Status', 'Severity', 'Date', 'Site', 'Permit', 'Parameter', 'Exceedance %', 'Penalty'];
    const rows = filtered.map((v) => [
      v.violation_type,
      v.status,
      v.severity,
      v.violation_date,
      v.site_name ?? '',
      v.permit_number ?? '',
      v.parameter_name ?? '',
      v.exceedance_pct?.toString() ?? '',
      (v.actual_penalty ?? v.estimated_penalty ?? '').toString(),
    ]);
    const csv = [headers, ...rows].map((r) => r.map((c) => `"${c}"`).join(',')).join('\n') + `\n\n"${DISCLAIMER}"`;
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance_violations_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    log('violation_export_csv', { count: filtered.length }, { module: 'compliance_violations', tableName: 'compliance_violations' });
  };

  const totalPenalties = statusCounts.total_penalties;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-red-500/20">
            <ShieldAlert className="w-6 h-6 text-red-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">Compliance Violations</h1>
            <p className="text-sm text-text-secondary">Violation database, NOVs, and enforcement actions</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-3 py-2 text-sm bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 text-text-secondary"
          >
            <Download className="w-4 h-4" />
            Export CSV
          </button>
          <button
            onClick={() => setShowCreate(!showCreate)}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium bg-red-500/20 text-red-300 border border-red-500/30 rounded-lg hover:bg-red-500/30"
          >
            <Plus className="w-4 h-4" />
            Record Violation
          </button>
        </div>
      </div>

      {/* KPI Row */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
        {[
          { key: 'all' as const, label: 'Total', count: violations.length },
          { key: 'open' as const, label: 'Open', count: statusCounts.open },
          { key: 'under_investigation' as const, label: 'Investigating', count: statusCounts.under_investigation },
          { key: 'reported' as const, label: 'Reported', count: statusCounts.reported },
          { key: 'resolved' as const, label: 'Resolved', count: statusCounts.resolved },
          { key: 'closed' as const, label: 'Closed', count: statusCounts.closed },
        ].map(({ key, label, count }) => (
          <button
            key={key}
            onClick={() => setStatusFilter(key)}
            className={clsx(
              'p-3 rounded-lg border text-left transition-all',
              statusFilter === key
                ? 'bg-white/10 border-white/20'
                : 'bg-white/[0.02] border-white/5 hover:bg-white/5',
            )}
          >
            <div className="text-xl font-bold text-white">{count}</div>
            <div className="text-xs text-text-secondary">{label}</div>
          </button>
        ))}
      </div>

      {/* Penalties Banner */}
      {totalPenalties > 0 && (
        <SpotlightCard className="p-4 flex items-center gap-3">
          <DollarSign className="w-5 h-5 text-amber-400" />
          <div>
            <span className="text-sm text-text-secondary">Total Penalties (estimated + actual): </span>
            <span className="text-lg font-bold text-amber-300">
              ${totalPenalties.toLocaleString()}
            </span>
          </div>
        </SpotlightCard>
      )}

      {/* Search */}
      <div className="relative">
        <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-secondary" />
        <input
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full pl-10 pr-4 py-2 bg-white/5 border border-white/10 rounded-lg text-white text-sm placeholder:text-text-secondary focus:border-red-500/50 focus:outline-none"
          placeholder="Search violations by site, permit, parameter..."
        />
      </div>

      {/* Create Form */}
      {showCreate && (
        <SpotlightCard className="p-6 space-y-4">
          <h3 className="text-lg font-semibold text-white">Record Violation</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm text-text-secondary mb-1">Type *</label>
              <select
                value={violationType}
                onChange={(e) => setViolationType(e.target.value as ViolationType)}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:border-red-500/50 focus:outline-none"
              >
                {Object.entries(TYPE_LABELS).map(([k, v]) => (
                  <option key={k} value={k}>{v}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm text-text-secondary mb-1">Severity</label>
              <select
                value={severity}
                onChange={(e) => setSeverity(e.target.value as ViolationSeverity)}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:border-red-500/50 focus:outline-none"
              >
                <option value="minor">Minor</option>
                <option value="moderate">Moderate</option>
                <option value="major">Major</option>
                <option value="critical">Critical</option>
              </select>
            </div>
            <div>
              <label className="block text-sm text-text-secondary mb-1">Violation Date *</label>
              <input
                type="date"
                value={violationDate}
                onChange={(e) => setViolationDate(e.target.value)}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:border-red-500/50 focus:outline-none"
              />
            </div>
            <div className="md:col-span-3">
              <label className="block text-sm text-text-secondary mb-1">Description</label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={2}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder:text-text-secondary focus:border-red-500/50 focus:outline-none resize-none"
                placeholder="Violation details..."
              />
            </div>
          </div>
          <div className="flex justify-end gap-2">
            <button onClick={() => setShowCreate(false)} className="px-4 py-2 text-sm text-text-secondary hover:text-white">
              Cancel
            </button>
            <button
              onClick={handleCreate}
              className="px-4 py-2 text-sm font-medium bg-red-500/20 text-red-300 border border-red-500/30 rounded-lg hover:bg-red-500/30"
            >
              Record Violation
            </button>
          </div>
        </SpotlightCard>
      )}

      {/* Violations List */}
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin h-8 w-8 border-2 border-red-400 border-t-transparent rounded-full" />
        </div>
      ) : filtered.length === 0 ? (
        <SpotlightCard className="p-12 text-center">
          <Filter className="w-8 h-8 text-text-secondary mx-auto mb-3" />
          <p className="text-text-secondary">No violations found</p>
        </SpotlightCard>
      ) : (
        <div className="space-y-2">
          {filtered.map((v) => (
            <Link key={v.id} to={`/compliance/violations/${v.id}`}>
              <SpotlightCard className="p-4 hover:bg-white/[0.04] transition-colors">
                <div className="flex items-center justify-between">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="text-white font-medium">{TYPE_LABELS[v.violation_type]}</h3>
                      {v.exceedance_pct && v.exceedance_pct > 0 && (
                        <span className="text-xs text-red-400 flex items-center gap-1">
                          <AlertTriangle className="w-3 h-3" />
                          {v.exceedance_pct.toFixed(1)}% over limit
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 text-xs text-text-secondary">
                      <span>{v.violation_date}</span>
                      {v.site_name && <span>{v.site_name}</span>}
                      {v.permit_number && <span>{v.permit_number}</span>}
                      {v.parameter_name && <span>{v.parameter_name}</span>}
                      {v.regulatory_agency && <span>{v.regulatory_agency}</span>}
                      {(v.actual_penalty ?? v.estimated_penalty) && (
                        <span className="text-amber-400">
                          ${(v.actual_penalty ?? v.estimated_penalty ?? 0).toLocaleString()}
                        </span>
                      )}
                    </div>
                    {v.description && (
                      <p className="text-xs text-text-secondary mt-1 truncate">{v.description}</p>
                    )}
                  </div>
                  <div className="flex items-center gap-2 ml-4">
                    <span className={clsx('px-2 py-0.5 rounded text-xs font-medium', SEVERITY_COLORS[v.severity])}>
                      {v.severity}
                    </span>
                    <span className={clsx('px-2 py-0.5 rounded text-xs font-medium border', STATUS_COLORS[v.status])}>
                      {STATUS_LABELS[v.status]}
                    </span>
                  </div>
                </div>
              </SpotlightCard>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}

export default ComplianceViolationsPage;
