import { useEffect, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Download, FileText, Loader2, Shield } from 'lucide-react';
import { toast } from 'sonner';
import { useSamplingGaps } from '@/hooks/useSamplingGaps';
import { useDefensibleMiss } from '@/hooks/useDefensibleMiss';
import { formatDefensibleMissMarkdown, type DefensibleMissPacket } from '@/lib/defensibleMiss';
import { useAuditLog } from '@/hooks/useAuditLog';

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function DefensibleMissPage() {
  const [searchParams] = useSearchParams();
  const deepLinkGapId = searchParams.get('gapId');
  const autoGeneratedRef = useRef<string | null>(null);

  const { rows, loading: gapsLoading } = useSamplingGaps();
  const {
    anomalies,
    storedPackets,
    loadingAnomalies,
    loadingStored,
    generating,
    generatingPdf,
    error,
    generatePacket,
    generatePdfPacket,
    fetchStoredPackets,
    getStoredPacketUrl,
  } = useDefensibleMiss();
  const { log } = useAuditLog();

  const missedRows = useMemo(
    () => rows.filter((r) => r.gap_kind === 'missed'),
    [rows],
  );

  const [selectedGapId, setSelectedGapId] = useState<string | null>(null);
  const [packet, setPacket] = useState<DefensibleMissPacket | null>(null);

  const selectedGap = useMemo(
    () => missedRows.find((r) => r.id === selectedGapId) ?? null,
    [missedRows, selectedGapId],
  );

  async function handleGenerate(gapId: string) {
    setSelectedGapId(gapId);
    void fetchStoredPackets(gapId);
    const result = await generatePacket(gapId);
    setPacket(result);
    if (!result) toast.error('Could not generate packet');
  }

  async function handleGeneratePdf() {
    if (!selectedGapId) return;
    const result = await generatePdfPacket(selectedGapId);
    if (!result) {
      toast.error('Could not generate PDF');
      return;
    }
    if (result.signed_url) {
      window.open(result.signed_url, '_blank', 'noopener,noreferrer');
    }
    toast.success('PDF stored in defensible-miss-packets bucket');
  }

  async function handleDownloadStored(storagePath: string) {
    const url = await getStoredPacketUrl(storagePath);
    if (!url) {
      toast.error('Could not create download link');
      return;
    }
    window.open(url, '_blank', 'noopener,noreferrer');
  }

  useEffect(() => {
    if (!deepLinkGapId || gapsLoading || autoGeneratedRef.current === deepLinkGapId) return;
    if (!missedRows.some((r) => r.id === deepLinkGapId)) return;
    autoGeneratedRef.current = deepLinkGapId;
    setSelectedGapId(deepLinkGapId);
    void fetchStoredPackets(deepLinkGapId);
    void generatePacket(deepLinkGapId).then((result) => {
      setPacket(result);
      if (!result) toast.error('Could not generate packet');
    });
  }, [deepLinkGapId, gapsLoading, missedRows, generatePacket, fetchStoredPackets]);

  function handleExport() {
    if (!packet || !selectedGap) return;
    const outfall = selectedGap.outfalls?.outfall_number ?? selectedGap.outfall_id.slice(0, 8);
    const param = selectedGap.parameters?.short_name ?? selectedGap.parameter_id.slice(0, 8);
    const md = formatDefensibleMissMarkdown(packet, outfall, param);
    downloadText(`defensible-miss-${selectedGap.scheduled_date}-${outfall}.md`, md);
    log('defensible_miss_packet_exported', { gap_id: packet.gap_id }, {
      module: 'environmental_compliance',
      tableName: 'sampling_gap_records',
      recordId: packet.gap_id,
    });
    toast.success('Packet exported');
  }

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-2">
          <Shield size={20} className="text-qo-accent" />
          <h2 className="text-xl font-semibold text-text-primary">Defensible-Miss Packets</h2>
        </div>
        <p className="mt-1 text-sm text-text-secondary">
          Flanking clean samples and collector access patterns — evidence for counsel review
        </p>
        <p className="mt-1 text-[10px] uppercase tracking-wide text-qo-ochre-text/90">
          DRAFT — not a legal conclusion or compliance certification
        </p>
      </div>

      {error && (
        <div className="rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-xs text-red-300">
          {error}
        </div>
      )}

      <div className="grid gap-4 lg:grid-cols-2">
        <section className="rounded-xl border border-black/[0.08] p-4 space-y-3">
          <h3 className="text-sm font-semibold text-text-primary">Missed events (from QW1 queue)</h3>
          {gapsLoading ? (
            <Loader2 className="mx-auto animate-spin text-text-muted" size={20} />
          ) : missedRows.length === 0 ? (
            <p className="text-xs text-text-muted">No open missed gaps — run gap detection first.</p>
          ) : (
            <ul className="space-y-2 max-h-72 overflow-y-auto">
              {missedRows.map((row) => (
                <li key={row.id}>
                  <button
                    type="button"
                    onClick={() => void handleGenerate(row.id)}
                    className="w-full rounded-lg border border-black/[0.08] bg-qo-nested px-3 py-2 text-left text-xs hover:bg-black/[0.04]"
                  >
                    <span className="font-medium text-text-primary">
                      {row.outfalls?.outfall_number ?? row.outfall_id.slice(0, 8)} ·{' '}
                      {row.parameters?.short_name ?? row.parameter_id.slice(0, 8)}
                    </span>
                    <span className="block text-text-muted mt-0.5">
                      Expected {row.scheduled_date} · {row.days_late}d late
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </section>

        <section className="rounded-xl border border-black/[0.08] p-4 space-y-3">
          <div className="flex items-center justify-between gap-2">
            <h3 className="text-sm font-semibold text-text-primary">Packet preview</h3>
            {packet && (
              <div className="flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={() => void handleGeneratePdf()}
                  disabled={generatingPdf}
                  className="inline-flex items-center gap-1 rounded-lg bg-qo-accent px-3 py-1.5 text-[10px] font-medium text-white hover:bg-qo-accent-hover disabled:cursor-not-allowed disabled:opacity-40"
                >
                  {generatingPdf ? (
                    <Loader2 size={12} className="animate-spin" />
                  ) : (
                    <FileText size={12} />
                  )}
                  Generate &amp; store PDF
                </button>
                <button
                  type="button"
                  onClick={handleExport}
                  className="inline-flex items-center gap-1 rounded-lg border border-black/[0.12] px-3 py-1.5 text-[10px] font-medium text-text-primary hover:bg-black/[0.05]"
                >
                  <FileText size={12} /> Export markdown
                </button>
              </div>
            )}
          </div>
          {generating && <Loader2 className="animate-spin text-text-muted" size={18} />}
          {!generating && !packet && (
            <p className="text-xs text-text-muted">Select a missed event to generate flanking sample cross-reference.</p>
          )}
          {packet && selectedGap && (
            <pre className="max-h-80 overflow-auto rounded-lg bg-black/30 p-3 text-[10px] text-text-secondary whitespace-pre-wrap">
              {formatDefensibleMissMarkdown(
                packet,
                selectedGap.outfalls?.outfall_number ?? selectedGap.outfall_id,
                selectedGap.parameters?.short_name ?? selectedGap.parameter_id,
              )}
            </pre>
          )}
          {selectedGapId && (
            <div className="space-y-2 border-t border-black/[0.06] pt-3">
              <h4 className="text-[10px] font-semibold uppercase tracking-wide text-text-muted">
                Stored packets
              </h4>
              {loadingStored ? (
                <Loader2 className="animate-spin text-text-muted" size={16} />
              ) : storedPackets.length === 0 ? (
                <p className="text-[10px] text-text-muted">No stored PDFs for this gap yet.</p>
              ) : (
                <ul className="space-y-1.5">
                  {storedPackets.map((stored) => (
                    <li
                      key={stored.id}
                      className="flex items-center justify-between gap-2 rounded-lg border border-black/[0.06] bg-qo-nested px-2 py-1.5"
                    >
                      <div className="min-w-0">
                        <p className="truncate text-[10px] font-medium text-text-primary">
                          {stored.file_name}
                        </p>
                        <p className="text-[9px] text-text-muted">
                          {new Date(stored.created_at).toLocaleString()} · {stored.format.toUpperCase()}
                          {stored.sha256_hash ? ` · ${stored.sha256_hash.slice(0, 12)}…` : ''}
                        </p>
                      </div>
                      {stored.storage_path && (
                        <button
                          type="button"
                          onClick={() => void handleDownloadStored(stored.storage_path!)}
                          className="inline-flex shrink-0 items-center gap-1 rounded border border-white/[0.1] px-2 py-1 text-[9px] text-text-primary hover:bg-black/[0.05]"
                        >
                          <Download size={10} /> PDF
                        </button>
                      )}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          )}
        </section>
      </div>

      <section className="rounded-xl border border-black/[0.08] p-4 space-y-3">
        <h3 className="text-sm font-semibold text-text-primary">Collector access anomalies</h3>
        <p className="text-xs text-text-muted">
          Field visits with access_issue outcome — habitual &quot;road closed / no access&quot; signal
        </p>
        {loadingAnomalies ? (
          <Loader2 className="animate-spin text-text-muted" size={18} />
        ) : anomalies.length === 0 ? (
          <p className="text-xs text-text-muted">No access-issue patterns in the lookback window.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-xs">
              <thead className="text-text-muted uppercase tracking-wide">
                <tr>
                  <th className="py-2 pr-3">Collector</th>
                  <th className="py-2 pr-3">Access issues</th>
                  <th className="py-2 pr-3">No discharge</th>
                  <th className="py-2 pr-3">Visits</th>
                  <th className="py-2">Rate</th>
                </tr>
              </thead>
              <tbody>
                {anomalies.map((a) => (
                  <tr key={a.collector_id} className="border-t border-black/[0.06]">
                    <td className="py-2 pr-3 text-text-primary">{a.collector_name}</td>
                    <td className="py-2 pr-3 tabular-nums">{a.access_issue_count}</td>
                    <td className="py-2 pr-3 tabular-nums">{a.no_discharge_count}</td>
                    <td className="py-2 pr-3 tabular-nums">{a.completed_visits}</td>
                    <td className="py-2 tabular-nums">{a.access_issue_rate_pct}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}

export default DefensibleMissPage;
