import { useState, useEffect } from 'react';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { useDocumentCompleteness, DOCUMENT_TYPE_LABELS } from '@/hooks/useDocumentCompleteness';
import { useAuditLog } from '@/hooks/useAuditLog';
import {
  FileCheck,
  Download,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  RefreshCw,
} from 'lucide-react';
import { clsx } from 'clsx';
import type { DocumentType, DocumentCompleteness } from '@/types/database';

const ALL_DOC_TYPES = Object.keys(DOCUMENT_TYPE_LABELS) as DocumentType[];

const DISCLAIMER = 'Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.';

export function DocumentCompletenessPage() {
  const {
    completenessResults,
    documents,
    loading,
    fetchDocuments,
    upsertDocument,
    fetchCompleteness,
  } = useDocumentCompleteness();
  const { log } = useAuditLog();

  const [selectedPermit, setSelectedPermit] = useState<string | null>(null);
  const [permitDocs, setPermitDocs] = useState<DocumentCompleteness[]>([]);

  useEffect(() => {
    if (selectedPermit) {
      fetchDocuments(selectedPermit);
    }
  }, [selectedPermit, fetchDocuments]);

  useEffect(() => {
    if (selectedPermit) {
      setPermitDocs(documents.filter((d) => d.permit_id === selectedPermit));
    }
  }, [documents, selectedPermit]);

  const handleToggleOnFile = async (permitId: string, docType: DocumentType, currentDoc?: DocumentCompleteness) => {
    const newOnFile = !(currentDoc?.is_on_file ?? false);
    await upsertDocument(permitId, docType, {
      is_on_file: newOnFile,
      is_current: newOnFile ? (currentDoc?.is_current ?? true) : false,
    });
    fetchDocuments(permitId);
  };

  const handleToggleCurrent = async (permitId: string, docType: DocumentType, currentDoc?: DocumentCompleteness) => {
    if (!currentDoc?.is_on_file) return;
    await upsertDocument(permitId, docType, {
      is_on_file: true,
      is_current: !currentDoc.is_current,
    });
    fetchDocuments(permitId);
  };

  const handleExport = () => {
    const headers = ['Permit', 'Site', 'Total Required', 'On File', 'Current', 'Expired', 'Completeness %'];
    const rows = completenessResults.map((r) => [
      r.permit_number,
      r.site_name,
      r.total_required.toString(),
      r.on_file.toString(),
      r.current_docs.toString(),
      r.expired_docs.toString(),
      r.completeness_pct.toString(),
    ]);
    const csv = [headers, ...rows].map((r) => r.map((c) => `"${c}"`).join(',')).join('\n') + `\n\n"${DISCLAIMER}"`;
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `document_completeness_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    log('document_completeness_exported', { count: completenessResults.length }, { module: 'audit', tableName: 'document_completeness' });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-teal-500/20">
            <FileCheck className="w-6 h-6 text-teal-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">Document Completeness</h1>
            <p className="text-sm text-text-secondary">Per-permit document coverage tracking</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-3 py-2 text-sm bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 text-text-secondary"
          >
            <Download className="w-4 h-4" />
            Export
          </button>
          <button
            onClick={() => fetchCompleteness()}
            className="flex items-center gap-2 px-3 py-2 text-sm bg-teal-500/20 text-teal-300 border border-teal-500/30 rounded-lg hover:bg-teal-500/30"
          >
            <RefreshCw className="w-4 h-4" />
            Recalculate
          </button>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin h-8 w-8 border-2 border-teal-400 border-t-transparent rounded-full" />
        </div>
      ) : completenessResults.length === 0 ? (
        <SpotlightCard className="p-12 text-center">
          <FileCheck className="w-8 h-8 text-text-secondary mx-auto mb-3" />
          <p className="text-text-secondary">No permits found. Upload permits to begin tracking.</p>
        </SpotlightCard>
      ) : (
        <>
          {/* Permit Summary Table */}
          <SpotlightCard className="p-4 overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-text-secondary border-b border-white/5">
                  <th className="pb-2 pr-4">Permit</th>
                  <th className="pb-2 pr-4">Site</th>
                  <th className="pb-2 pr-4 text-right">Required</th>
                  <th className="pb-2 pr-4 text-right">On File</th>
                  <th className="pb-2 pr-4 text-right">Current</th>
                  <th className="pb-2 pr-4 text-right">Expired</th>
                  <th className="pb-2 text-right">Completeness</th>
                </tr>
              </thead>
              <tbody>
                {completenessResults.map((r) => (
                  <tr
                    key={r.permit_id}
                    onClick={() => setSelectedPermit(r.permit_id === selectedPermit ? null : r.permit_id)}
                    className={clsx(
                      'border-b border-white/[0.03] cursor-pointer hover:bg-white/[0.02]',
                      selectedPermit === r.permit_id && 'bg-white/[0.04]',
                    )}
                  >
                    <td className="py-2 pr-4 text-white font-medium">{r.permit_number}</td>
                    <td className="py-2 pr-4 text-text-secondary">{r.site_name}</td>
                    <td className="py-2 pr-4 text-right text-white">{r.total_required}</td>
                    <td className="py-2 pr-4 text-right text-white">{r.on_file}</td>
                    <td className="py-2 pr-4 text-right text-emerald-400">{r.current_docs}</td>
                    <td className="py-2 pr-4 text-right">
                      <span className={clsx(r.expired_docs > 0 ? 'text-red-400' : 'text-emerald-400')}>
                        {r.expired_docs}
                      </span>
                    </td>
                    <td className="py-2 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <div className="w-16 h-1.5 bg-white/10 rounded-full overflow-hidden">
                          <div
                            className={clsx(
                              'h-full rounded-full',
                              r.completeness_pct >= 90 ? 'bg-emerald-500' : r.completeness_pct >= 60 ? 'bg-amber-500' : 'bg-red-500',
                            )}
                            style={{ width: `${r.completeness_pct}%` }}
                          />
                        </div>
                        <span className={clsx(
                          'text-xs font-medium',
                          r.completeness_pct >= 90 ? 'text-emerald-400' : r.completeness_pct >= 60 ? 'text-amber-400' : 'text-red-400',
                        )}>
                          {r.completeness_pct}%
                        </span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </SpotlightCard>

          {/* Document Detail for Selected Permit */}
          {selectedPermit && (
            <SpotlightCard className="p-4">
              <h3 className="text-sm font-medium text-text-secondary mb-3">
                Document Details — {completenessResults.find((r) => r.permit_id === selectedPermit)?.permit_number}
              </h3>
              <div className="space-y-1">
                {ALL_DOC_TYPES.map((docType) => {
                  const doc = permitDocs.find((d) => d.document_type === docType);
                  const isExpired = doc?.expiry_date && new Date(doc.expiry_date) < new Date();

                  return (
                    <div
                      key={docType}
                      className="flex items-center justify-between py-2 px-2 rounded hover:bg-white/[0.02]"
                    >
                      <span className="text-sm text-white">{DOCUMENT_TYPE_LABELS[docType]}</span>
                      <div className="flex items-center gap-3">
                        {isExpired && (
                          <AlertTriangle className="w-4 h-4 text-red-400" />
                        )}
                        <button
                          onClick={() => handleToggleOnFile(selectedPermit, docType, doc)}
                          className="flex items-center gap-1 text-xs"
                          title="On file"
                        >
                          {doc?.is_on_file ? (
                            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                          ) : (
                            <XCircle className="w-4 h-4 text-gray-500" />
                          )}
                          <span className={doc?.is_on_file ? 'text-emerald-400' : 'text-gray-500'}>
                            On File
                          </span>
                        </button>
                        <button
                          onClick={() => handleToggleCurrent(selectedPermit, docType, doc)}
                          className={clsx(
                            'flex items-center gap-1 text-xs',
                            !doc?.is_on_file && 'opacity-30 cursor-not-allowed',
                          )}
                          title="Current/up-to-date"
                          disabled={!doc?.is_on_file}
                        >
                          {doc?.is_current ? (
                            <CheckCircle2 className="w-4 h-4 text-cyan-400" />
                          ) : (
                            <XCircle className="w-4 h-4 text-gray-500" />
                          )}
                          <span className={doc?.is_current ? 'text-cyan-400' : 'text-gray-500'}>
                            Current
                          </span>
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </SpotlightCard>
          )}
        </>
      )}
    </div>
  );
}

export default DocumentCompletenessPage;
