import { useState } from 'react';
import {
  Phone, Plus, Shield, AlertTriangle, CheckCircle2,
  ChevronDown, ChevronUp, Trash2, PhoneCall, Mail, X,
} from 'lucide-react';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { useEmergencyProcedures, CONTACT_ROLE_LABELS, INCIDENT_TYPE_LABELS, SEVERITY_LABELS } from '@/hooks/useEmergencyProcedures';
import { useAuditLog } from '@/hooks/useAuditLog';
import type {
  EmergencyContactRole,
  ContactAvailability,
  EmergencyIncidentType,
  ProcedureSeverityLevel,
  ProcedureStep,
  EmergencyProcedure,
} from '@/types/database';

type Tab = 'contacts' | 'procedures';

const AVAILABILITY_LABELS: Record<ContactAvailability, string> = {
  '24/7': '24/7',
  business_hours: 'Business Hours',
  on_call: 'On Call',
  scheduled: 'Scheduled',
};

const SEVERITY_COLORS: Record<ProcedureSeverityLevel, string> = {
  all: 'bg-gray-500/20 text-gray-300',
  minor: 'bg-blue-500/20 text-blue-300',
  moderate: 'bg-yellow-500/20 text-yellow-300',
  major: 'bg-orange-500/20 text-orange-300',
  critical: 'bg-red-500/20 text-red-300',
};

export function EmergencyProceduresPage() {
  const {
    contacts, procedures, loading,
    createContact, updateContact, deleteContact,
    createProcedure, updateProcedure, reviewProcedure,
  } = useEmergencyProcedures();
  const { log } = useAuditLog();

  const [tab, setTab] = useState<Tab>('contacts');
  const [showContactForm, setShowContactForm] = useState(false);
  const [showProcedureForm, setShowProcedureForm] = useState(false);
  const [expandedProcedure, setExpandedProcedure] = useState<string | null>(null);

  // Contact form state
  const [cName, setCName] = useState('');
  const [cRole, setCRole] = useState<EmergencyContactRole>('site_manager');
  const [cOrg, setCOrg] = useState('');
  const [cPhone, setCPhone] = useState('');
  const [cEmail, setCEmail] = useState('');
  const [cAvail, setCAvail] = useState<ContactAvailability>('business_hours');
  const [cPrimary, setCPrimary] = useState(false);

  // Procedure form state
  const [pTitle, setPTitle] = useState('');
  const [pType, setPType] = useState<EmergencyIncidentType>('spill');
  const [pSeverity, setPSeverity] = useState<ProcedureSeverityLevel>('all');
  const [pDesc, setPDesc] = useState('');
  const [pSteps, setPSteps] = useState<ProcedureStep[]>([{ order: 1, action: '', responsible: '', timeframe: '' }]);

  const resetContactForm = () => {
    setCName(''); setCRole('site_manager'); setCOrg(''); setCPhone(''); setCEmail('');
    setCAvail('business_hours'); setCPrimary(false); setShowContactForm(false);
  };

  const resetProcedureForm = () => {
    setPTitle(''); setPType('spill'); setPSeverity('all'); setPDesc('');
    setPSteps([{ order: 1, action: '', responsible: '', timeframe: '' }]);
    setShowProcedureForm(false);
  };

  const handleCreateContact = async () => {
    if (!cName.trim()) return;
    await createContact({
      contact_name: cName.trim(),
      contact_role: cRole,
      organization_name: cOrg.trim() || undefined,
      phone_primary: cPhone.trim() || undefined,
      email: cEmail.trim() || undefined,
      availability: cAvail,
      is_primary: cPrimary,
    });
    resetContactForm();
  };

  const handleCreateProcedure = async () => {
    if (!pTitle.trim()) return;
    const validSteps = pSteps.filter(s => s.action.trim());
    await createProcedure({
      title: pTitle.trim(),
      incident_type: pType,
      severity_level: pSeverity,
      description: pDesc.trim() || undefined,
      steps: validSteps.map((s, i) => ({ ...s, order: i + 1 })),
    });
    resetProcedureForm();
  };

  const addStep = () => {
    setPSteps(prev => [...prev, { order: prev.length + 1, action: '', responsible: '', timeframe: '' }]);
  };

  const updateStep = (idx: number, field: keyof ProcedureStep, value: string) => {
    setPSteps(prev => prev.map((s, i) => i === idx ? { ...s, [field]: value } : s));
  };

  const removeStep = (idx: number) => {
    setPSteps(prev => prev.filter((_, i) => i !== idx));
  };

  const handleExportCSV = () => {
    if (tab === 'contacts') {
      const headers = ['Name', 'Role', 'Organization', 'Phone', 'Email', 'Availability', 'Primary', 'Active'];
      const rows = contacts.map(c => [
        c.contact_name, CONTACT_ROLE_LABELS[c.contact_role], c.organization_name ?? '',
        c.phone_primary ?? '', c.email ?? '', AVAILABILITY_LABELS[c.availability],
        c.is_primary ? 'Yes' : 'No', c.is_active ? 'Yes' : 'No',
      ]);
      const csv = [headers, ...rows].map(r => r.map(v => `"${v}"`).join(',')).join('\n');
      const blob = new Blob([csv + '\n\nGenerated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.'], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `emergency-contacts-${new Date().toISOString().slice(0, 10)}.csv`;
      a.click(); URL.revokeObjectURL(url);
      log('emergency_contacts_exported', { count: contacts.length }, { module: 'emergency', tableName: 'emergency_contacts' });
    } else {
      const headers = ['Title', 'Type', 'Severity', 'Active', 'Last Reviewed', 'Steps'];
      const rows = procedures.map(p => [
        p.title, INCIDENT_TYPE_LABELS[p.incident_type], SEVERITY_LABELS[p.severity_level],
        p.is_active ? 'Yes' : 'No', p.last_reviewed_at ? new Date(p.last_reviewed_at).toLocaleDateString() : 'Never',
        String(p.steps?.length ?? 0),
      ]);
      const csv = [headers, ...rows].map(r => r.map(v => `"${v}"`).join(',')).join('\n');
      const blob = new Blob([csv + '\n\nGenerated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.'], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `emergency-procedures-${new Date().toISOString().slice(0, 10)}.csv`;
      a.click(); URL.revokeObjectURL(url);
      log('emergency_procedures_exported', { count: procedures.length }, { module: 'emergency', tableName: 'emergency_procedures' });
    }
  };

  const activeContacts = contacts.filter(c => c.is_active);
  const primaryContacts = contacts.filter(c => c.is_primary && c.is_active);
  const activeProcedures = procedures.filter(p => p.is_active);
  const needsReview = procedures.filter(p => {
    if (!p.last_reviewed_at) return true;
    const daysSince = (Date.now() - new Date(p.last_reviewed_at).getTime()) / 86400000;
    return daysSince > 90;
  });

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-text-primary font-display">Emergency Recovery</h1>
          <p className="text-sm text-text-secondary mt-1">Emergency contacts, response procedures, and notification chains</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={handleExportCSV} className="px-3 py-1.5 text-xs bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 text-text-secondary">
            Export CSV
          </button>
          <button
            onClick={() => tab === 'contacts' ? setShowContactForm(true) : setShowProcedureForm(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-primary/20 border border-primary/30 rounded-lg hover:bg-primary/30 text-primary"
          >
            <Plus className="w-3.5 h-3.5" />
            {tab === 'contacts' ? 'Add Contact' : 'Add Procedure'}
          </button>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <Phone className="w-4 h-4 text-cyan-400" />
            <span className="text-xs text-text-secondary">Active Contacts</span>
          </div>
          <p className="text-xl font-bold text-text-primary">{activeContacts.length}</p>
        </SpotlightCard>
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <PhoneCall className="w-4 h-4 text-green-400" />
            <span className="text-xs text-text-secondary">Primary Contacts</span>
          </div>
          <p className="text-xl font-bold text-text-primary">{primaryContacts.length}</p>
        </SpotlightCard>
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <Shield className="w-4 h-4 text-indigo-400" />
            <span className="text-xs text-text-secondary">Active Procedures</span>
          </div>
          <p className="text-xl font-bold text-text-primary">{activeProcedures.length}</p>
        </SpotlightCard>
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            <span className="text-xs text-text-secondary">Needs Review</span>
          </div>
          <p className="text-xl font-bold text-text-primary">{needsReview.length}</p>
        </SpotlightCard>
      </div>

      {/* Tab Bar */}
      <div className="flex gap-1 bg-white/5 rounded-lg p-1">
        {(['contacts', 'procedures'] as Tab[]).map(t => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`flex-1 px-4 py-2 text-sm rounded-md transition-colors ${
              tab === t ? 'bg-white/10 text-text-primary' : 'text-text-secondary hover:text-text-primary'
            }`}
          >
            {t === 'contacts' ? 'Emergency Contacts' : 'Response Procedures'}
          </button>
        ))}
      </div>

      {/* Contact Form */}
      {showContactForm && (
        <SpotlightCard className="p-4 space-y-3 border border-primary/20">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-text-primary">New Emergency Contact</h3>
            <button onClick={resetContactForm} className="text-text-secondary hover:text-text-primary"><X className="w-4 h-4" /></button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <input value={cName} onChange={e => setCName(e.target.value)} placeholder="Contact Name *" className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary placeholder:text-text-secondary/50" />
            <select value={cRole} onChange={e => setCRole(e.target.value as EmergencyContactRole)} className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary">
              {Object.entries(CONTACT_ROLE_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
            </select>
            <input value={cOrg} onChange={e => setCOrg(e.target.value)} placeholder="Organization" className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary placeholder:text-text-secondary/50" />
            <input value={cPhone} onChange={e => setCPhone(e.target.value)} placeholder="Phone" className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary placeholder:text-text-secondary/50" />
            <input value={cEmail} onChange={e => setCEmail(e.target.value)} placeholder="Email" className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary placeholder:text-text-secondary/50" />
            <select value={cAvail} onChange={e => setCAvail(e.target.value as ContactAvailability)} className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary">
              {Object.entries(AVAILABILITY_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
            </select>
          </div>
          <label className="flex items-center gap-2 text-sm text-text-secondary">
            <input type="checkbox" checked={cPrimary} onChange={e => setCPrimary(e.target.checked)} className="rounded" />
            Primary contact
          </label>
          <button onClick={handleCreateContact} disabled={!cName.trim()} className="px-4 py-2 text-sm bg-primary/20 border border-primary/30 rounded-lg hover:bg-primary/30 text-primary disabled:opacity-50">
            Create Contact
          </button>
        </SpotlightCard>
      )}

      {/* Procedure Form */}
      {showProcedureForm && (
        <SpotlightCard className="p-4 space-y-3 border border-primary/20">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-text-primary">New Emergency Procedure</h3>
            <button onClick={resetProcedureForm} className="text-text-secondary hover:text-text-primary"><X className="w-4 h-4" /></button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <input value={pTitle} onChange={e => setPTitle(e.target.value)} placeholder="Procedure Title *" className="md:col-span-3 px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary placeholder:text-text-secondary/50" />
            <select value={pType} onChange={e => setPType(e.target.value as EmergencyIncidentType)} className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary">
              {Object.entries(INCIDENT_TYPE_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
            </select>
            <select value={pSeverity} onChange={e => setPSeverity(e.target.value as ProcedureSeverityLevel)} className="px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary">
              {Object.entries(SEVERITY_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
            </select>
            <textarea value={pDesc} onChange={e => setPDesc(e.target.value)} placeholder="Description" rows={2} className="md:col-span-3 px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-text-primary placeholder:text-text-secondary/50" />
          </div>
          <div className="space-y-2">
            <p className="text-xs text-text-secondary font-medium">Response Steps</p>
            {pSteps.map((step, idx) => (
              <div key={idx} className="flex gap-2 items-start">
                <span className="text-xs text-text-secondary mt-2.5 w-6">{idx + 1}.</span>
                <input value={step.action} onChange={e => updateStep(idx, 'action', e.target.value)} placeholder="Action" className="flex-1 px-3 py-1.5 bg-white/5 border border-white/10 rounded text-sm text-text-primary placeholder:text-text-secondary/50" />
                <input value={step.responsible} onChange={e => updateStep(idx, 'responsible', e.target.value)} placeholder="Responsible" className="w-32 px-3 py-1.5 bg-white/5 border border-white/10 rounded text-sm text-text-primary placeholder:text-text-secondary/50" />
                <input value={step.timeframe} onChange={e => updateStep(idx, 'timeframe', e.target.value)} placeholder="Timeframe" className="w-28 px-3 py-1.5 bg-white/5 border border-white/10 rounded text-sm text-text-primary placeholder:text-text-secondary/50" />
                {pSteps.length > 1 && (
                  <button onClick={() => removeStep(idx)} className="text-red-400 hover:text-red-300 mt-1.5"><Trash2 className="w-3.5 h-3.5" /></button>
                )}
              </div>
            ))}
            <button onClick={addStep} className="text-xs text-primary hover:text-primary/80">+ Add step</button>
          </div>
          <button onClick={handleCreateProcedure} disabled={!pTitle.trim()} className="px-4 py-2 text-sm bg-primary/20 border border-primary/30 rounded-lg hover:bg-primary/30 text-primary disabled:opacity-50">
            Create Procedure
          </button>
        </SpotlightCard>
      )}

      {/* Contacts List */}
      {tab === 'contacts' && (
        <div className="space-y-2">
          {contacts.length === 0 && (
            <p className="text-center text-text-secondary text-sm py-8">No emergency contacts configured. Add your first contact above.</p>
          )}
          {contacts.map(c => (
            <SpotlightCard key={c.id} className="p-4">
              <div className="flex items-start justify-between">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-semibold text-text-primary truncate">{c.contact_name}</h3>
                    {c.is_primary && <span className="px-1.5 py-0.5 text-[10px] bg-green-500/20 text-green-300 rounded">PRIMARY</span>}
                    {!c.is_active && <span className="px-1.5 py-0.5 text-[10px] bg-red-500/20 text-red-300 rounded">INACTIVE</span>}
                  </div>
                  <p className="text-xs text-text-secondary mt-0.5">
                    {CONTACT_ROLE_LABELS[c.contact_role]}
                    {c.organization_name ? ` · ${c.organization_name}` : ''}
                    {` · ${AVAILABILITY_LABELS[c.availability]}`}
                  </p>
                  <div className="flex items-center gap-4 mt-2">
                    {c.phone_primary && (
                      <span className="flex items-center gap-1 text-xs text-text-secondary">
                        <PhoneCall className="w-3 h-3" />{c.phone_primary}
                      </span>
                    )}
                    {c.email && (
                      <span className="flex items-center gap-1 text-xs text-text-secondary">
                        <Mail className="w-3 h-3" />{c.email}
                      </span>
                    )}
                  </div>
                </div>
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => updateContact(c.id, { is_active: !c.is_active })}
                    className={`px-2 py-1 text-xs rounded ${c.is_active ? 'text-amber-400 hover:bg-amber-500/10' : 'text-green-400 hover:bg-green-500/10'}`}
                  >
                    {c.is_active ? 'Deactivate' : 'Activate'}
                  </button>
                  <button onClick={() => deleteContact(c.id)} className="p-1 text-red-400 hover:bg-red-500/10 rounded">
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </SpotlightCard>
          ))}
        </div>
      )}

      {/* Procedures List */}
      {tab === 'procedures' && (
        <div className="space-y-2">
          {procedures.length === 0 && (
            <p className="text-center text-text-secondary text-sm py-8">No emergency procedures configured. Add your first procedure above.</p>
          )}
          {procedures.map(p => (
            <ProcedureCard
              key={p.id}
              procedure={p}
              expanded={expandedProcedure === p.id}
              onToggle={() => setExpandedProcedure(prev => prev === p.id ? null : p.id)}
              onReview={() => reviewProcedure(p.id)}
              onToggleActive={() => updateProcedure(p.id, { is_active: !p.is_active })}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function ProcedureCard({
  procedure: p, expanded, onToggle, onReview, onToggleActive,
}: {
  procedure: EmergencyProcedure;
  expanded: boolean;
  onToggle: () => void;
  onReview: () => void;
  onToggleActive: () => void;
}) {
  const daysSinceReview = p.last_reviewed_at
    ? Math.floor((Date.now() - new Date(p.last_reviewed_at).getTime()) / 86400000)
    : null;
  const stale = daysSinceReview === null || daysSinceReview > 90;

  return (
    <SpotlightCard className="p-4">
      <div className="flex items-start justify-between">
        <button onClick={onToggle} className="flex-1 text-left min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <h3 className="text-sm font-semibold text-text-primary">{p.title}</h3>
            <span className={`px-1.5 py-0.5 text-[10px] rounded ${SEVERITY_COLORS[p.severity_level]}`}>
              {SEVERITY_LABELS[p.severity_level]}
            </span>
            <span className="px-1.5 py-0.5 text-[10px] bg-white/5 text-text-secondary rounded">
              {INCIDENT_TYPE_LABELS[p.incident_type]}
            </span>
            {!p.is_active && <span className="px-1.5 py-0.5 text-[10px] bg-red-500/20 text-red-300 rounded">INACTIVE</span>}
            {stale && p.is_active && <span className="px-1.5 py-0.5 text-[10px] bg-amber-500/20 text-amber-300 rounded">REVIEW NEEDED</span>}
          </div>
          <p className="text-xs text-text-secondary mt-1">
            {p.steps?.length ?? 0} steps
            {p.last_reviewed_at ? ` · Reviewed ${daysSinceReview}d ago` : ' · Never reviewed'}
          </p>
        </button>
        <div className="flex items-center gap-1">
          <button onClick={onReview} className="flex items-center gap-1 px-2 py-1 text-xs text-green-400 hover:bg-green-500/10 rounded">
            <CheckCircle2 className="w-3 h-3" />Review
          </button>
          <button onClick={onToggleActive} className={`px-2 py-1 text-xs rounded ${p.is_active ? 'text-amber-400 hover:bg-amber-500/10' : 'text-green-400 hover:bg-green-500/10'}`}>
            {p.is_active ? 'Deactivate' : 'Activate'}
          </button>
          {expanded ? <ChevronUp className="w-4 h-4 text-text-secondary" /> : <ChevronDown className="w-4 h-4 text-text-secondary" />}
        </div>
      </div>

      {expanded && (
        <div className="mt-3 pt-3 border-t border-white/5 space-y-3">
          {p.description && <p className="text-xs text-text-secondary">{p.description}</p>}

          {p.steps && p.steps.length > 0 && (
            <div>
              <p className="text-xs font-medium text-text-secondary mb-2">Response Steps</p>
              <div className="space-y-1.5">
                {p.steps.map((s, i) => (
                  <div key={i} className="flex gap-2 text-xs">
                    <span className="text-text-secondary w-5 text-right">{s.order}.</span>
                    <div className="flex-1">
                      <span className="text-text-primary">{s.action}</span>
                      {s.responsible && <span className="text-text-secondary ml-2">— {s.responsible}</span>}
                      {s.timeframe && <span className="text-cyan-400/70 ml-2">[{s.timeframe}]</span>}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {p.decree_paragraphs && p.decree_paragraphs.length > 0 && (
            <p className="text-xs text-text-secondary">
              <span className="font-medium">Consent Decree:</span> ¶{p.decree_paragraphs.join(', ¶')}
            </p>
          )}
          {p.regulatory_requirements && (
            <p className="text-xs text-text-secondary">
              <span className="font-medium">Regulatory:</span> {p.regulatory_requirements}
            </p>
          )}
          {p.reporting_deadlines && (
            <p className="text-xs text-text-secondary">
              <span className="font-medium">Reporting Deadline:</span> {p.reporting_deadlines}
            </p>
          )}
        </div>
      )}
    </SpotlightCard>
  );
}
