import { useState, useMemo, useCallback } from 'react';
import { BarChart3, Download, Table2, LineChart } from 'lucide-react';
import { toast } from 'sonner';
import { useRainEvents } from '@/hooks/useRainEvents';
import { useWeatherStations } from '@/hooks/useWeatherStations';
import { useAuditLog } from '@/hooks/useAuditLog';
import { PrecipitationChart } from '@/components/weather/PrecipitationChart';
import { ReadingsTable } from '@/components/weather/ReadingsTable';
import { cn } from '@/lib/cn';

type ViewTab = 'chart' | 'table';

export function PrecipitationDataPage() {
  const { readings, loading } = useRainEvents();
  const { stations } = useWeatherStations();
  const { log } = useAuditLog();

  const [selectedStationId, setSelectedStationId] = useState<string>('');
  const [activeTab, setActiveTab] = useState<ViewTab>('chart');

  // Filter readings by selected station
  const filteredReadings = useMemo(() => {
    if (!selectedStationId) return readings;
    return readings.filter((r) => r.weather_station_id === selectedStationId);
  }, [readings, selectedStationId]);

  // Station lookup for CSV export
  const stationMap = useMemo(() => {
    const m = new Map<string, string>();
    for (const s of stations) {
      m.set(s.id, s.station_name);
    }
    return m;
  }, [stations]);

  // CSV export handler
  const handleExportCsv = useCallback(() => {
    if (filteredReadings.length === 0) {
      toast.error('No readings to export');
      return;
    }

    const header = 'Date,Time,Station,Rainfall (in),Duration (hrs),Source,Quality Flag';
    const rows = filteredReadings
      .slice()
      .sort((a, b) => b.reading_date.localeCompare(a.reading_date))
      .map((r) => {
        const stationName = stationMap.get(r.weather_station_id) ?? 'Unknown';
        const time = r.reading_time ?? '';
        const duration = r.duration_hours != null ? r.duration_hours.toFixed(1) : '';
        const flag = r.data_quality_flag ?? '';
        return `${r.reading_date},${time},"${stationName}",${r.rainfall_inches.toFixed(2)},${duration},${r.source_type},${flag}`;
      });

    const disclaimer =
      '"Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission."';
    const csv = [header, ...rows, '', disclaimer].join('\n');

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `precipitation-data-${new Date().toISOString().slice(0, 10)}.csv`;
    link.click();
    URL.revokeObjectURL(url);

    log('precipitation_data_export_csv', {
      reading_count: filteredReadings.length,
      station_filter: selectedStationId || 'all',
    }, {
      module: 'rain_events',
      tableName: 'precipitation_readings',
    });

    toast.success(`Exported ${filteredReadings.length} readings`);
  }, [filteredReadings, stationMap, selectedStationId, log]);

  const tabs: { value: ViewTab; label: string; icon: typeof LineChart }[] = [
    { value: 'chart', label: 'Chart', icon: LineChart },
    { value: 'table', label: 'Table', icon: Table2 },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <BarChart3 className="h-6 w-6 text-teal-400" />
          <div>
            <h1 className="text-2xl font-semibold text-white">Precipitation Data</h1>
            <p className="text-sm text-text-muted mt-0.5">
              Precipitation readings, station data, and rainfall history
            </p>
          </div>
        </div>

        {/* Export CSV */}
        <button
          onClick={handleExportCsv}
          disabled={filteredReadings.length === 0}
          className={cn(
            'flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors',
            'bg-white/[0.04] border border-white/[0.06] text-text-secondary',
            'hover:bg-white/[0.08] hover:text-text-primary',
            'disabled:opacity-40 disabled:cursor-not-allowed',
          )}
        >
          <Download className="h-4 w-4" />
          Export CSV
        </button>
      </div>

      {/* Filters & Tabs */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        {/* Station Filter */}
        <div className="flex items-center gap-2">
          <label htmlFor="station-filter" className="text-xs text-text-muted">
            Station:
          </label>
          <select
            id="station-filter"
            value={selectedStationId}
            onChange={(e) => setSelectedStationId(e.target.value)}
            className={cn(
              'rounded-lg px-3 py-1.5 text-sm text-text-primary',
              'bg-white/[0.04] border border-white/[0.06]',
              'focus:outline-none focus:ring-1 focus:ring-sky-500/40',
            )}
          >
            <option value="">All Stations</option>
            {stations.map((s) => (
              <option key={s.id} value={s.id}>
                {s.station_name}
              </option>
            ))}
          </select>
        </div>

        {/* View Tabs */}
        <div className="flex items-center gap-1 rounded-xl bg-white/[0.02] border border-white/[0.06] p-1">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.value}
                onClick={() => setActiveTab(tab.value)}
                className={cn(
                  'flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors',
                  activeTab === tab.value
                    ? 'bg-white/[0.08] text-text-primary'
                    : 'text-text-muted hover:text-text-secondary hover:bg-white/[0.04]',
                )}
              >
                <Icon className="h-3.5 w-3.5" />
                {tab.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Content Card */}
      <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] backdrop-blur-xl p-6">
        {loading ? (
          <div className="flex items-center justify-center h-64 text-text-muted text-sm">
            <div className="flex items-center gap-2">
              <div className="h-4 w-4 rounded-full border-2 border-sky-400/40 border-t-sky-400 animate-spin" />
              Loading precipitation data...
            </div>
          </div>
        ) : activeTab === 'chart' ? (
          <PrecipitationChart
            readings={filteredReadings}
            stations={stations}
            selectedStationId={selectedStationId || undefined}
          />
        ) : (
          <ReadingsTable readings={filteredReadings} stations={stations} />
        )}
      </div>
    </div>
  );
}

export default PrecipitationDataPage;
