import { useState } from 'react';
import {
  Activity, Database, Shield, Clock, AlertTriangle, CheckCircle2,
  XCircle, Play, Archive,
} from 'lucide-react';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { useSystemHealth } from '@/hooks/useSystemHealth';
import { useAuditLog } from '@/hooks/useAuditLog';
import type { DataIntegrityCheck, IntegrityCheckResult } from '@/types/database';

type Tab = 'integrity' | 'retention' | 'health';

const STATUS_ICON: Record<string, { icon: typeof CheckCircle2; color: string }> = {
  passed: { icon: CheckCircle2, color: 'text-green-400' },
  warnings: { icon: AlertTriangle, color: 'text-amber-400' },
  failed: { icon: XCircle, color: 'text-red-400' },
  running: { icon: Activity, color: 'text-cyan-400' },
};

const CHECK_STATUS_COLOR: Record<string, string> = {
  pass: 'text-green-400',
  warn: 'text-amber-400',
  fail: 'text-red-400',
};

export function SystemHealthPage() {
  const {
    integrityChecks, retentionPolicies, healthLogs,
    loading, runningCheck,
    runIntegrityCheck, updateRetentionPolicy,
  } = useSystemHealth();
  const { log } = useAuditLog();

  const [tab, setTab] = useState<Tab>('integrity');
  const [expandedCheck, setExpandedCheck] = useState<string | null>(null);

  const latestCheck = integrityChecks[0] ?? null;
  const latestHealth = healthLogs[0] ?? null;
  const enforcedPolicies = retentionPolicies.filter(p => p.is_enforced);
  const totalOutsidePolicy = retentionPolicies.reduce((s, p) => s + (p.records_outside_policy ?? 0), 0);

  const handleExportCSV = () => {
    if (tab === 'integrity') {
      const headers = ['Run Date', 'Type', 'Status', 'Total', 'Passed', 'Warned', 'Failed', 'Duration (ms)'];
      const rows = integrityChecks.map(c => [
        new Date(c.created_at).toLocaleString(), c.run_type, c.status,
        String(c.checks_total), String(c.checks_passed), String(c.checks_warned),
        String(c.checks_failed), String(c.duration_ms ?? ''),
      ]);
      exportCSV(headers, rows, 'integrity-checks');
    } else if (tab === 'retention') {
      const headers = ['Record Type', 'Display Name', 'Retention (years)', 'Regulatory Basis', 'Enforced', 'Within Policy', 'Outside Policy'];
      const rows = retentionPolicies.map(p => [
        p.record_type, p.display_name, String(p.retention_years), p.regulatory_basis,
        p.is_enforced ? 'Yes' : 'No', String(p.records_within_policy ?? 0),
        String(p.records_outside_policy ?? 0),
      ]);
      exportCSV(headers, rows, 'retention-policies');
    } else {
      const headers = ['Snapshot', 'DB Size (MB)', 'Storage (MB)', 'Active Users 24h', 'Errors 24h', 'Avg Response (ms)'];
      const rows = healthLogs.map(h => [
        new Date(h.snapshot_at).toLocaleString(), String(h.db_size_mb ?? ''),
        String(h.storage_usage_mb ?? ''), String(h.active_users_24h ?? ''),
        String(h.error_count_24h ?? ''), String(h.avg_response_ms ?? ''),
      ]);
      exportCSV(headers, rows, 'system-health');
    }
    log('system_health_exported', { tab }, { module: 'system_health', tableName: 'system_health_logs' });
  };

  const exportCSV = (headers: string[], rows: string[][], filename: string) => {
    const csv = [headers, ...rows].map(r => r.map(v => `"${v}"`).join(',')).join('\n');
    const blob = new Blob([csv + '\n\nGenerated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.'], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${filename}-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click(); URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-text-primary font-display">System Health</h1>
          <p className="text-sm text-text-secondary mt-1">Data integrity checks, retention policies, and system monitoring</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={handleExportCSV} className="px-3 py-1.5 text-xs bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 text-text-secondary">
            Export CSV
          </button>
          {tab === 'integrity' && (
            <button
              onClick={runIntegrityCheck}
              disabled={runningCheck}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-primary/20 border border-primary/30 rounded-lg hover:bg-primary/30 text-primary disabled:opacity-50"
            >
              <Play className="w-3.5 h-3.5" />
              {runningCheck ? 'Running…' : 'Run Check'}
            </button>
          )}
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <Shield className="w-4 h-4 text-cyan-400" />
            <span className="text-xs text-text-secondary">Last Check</span>
          </div>
          {latestCheck ? (
            <>
              <p className={`text-xl font-bold ${STATUS_ICON[latestCheck.status]?.color ?? 'text-text-primary'}`}>
                {latestCheck.status.charAt(0).toUpperCase() + latestCheck.status.slice(1)}
              </p>
              <p className="text-[10px] text-text-secondary">{new Date(latestCheck.created_at).toLocaleString()}</p>
            </>
          ) : (
            <p className="text-sm text-text-secondary">No checks run</p>
          )}
        </SpotlightCard>
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <Database className="w-4 h-4 text-indigo-400" />
            <span className="text-xs text-text-secondary">DB Size</span>
          </div>
          <p className="text-xl font-bold text-text-primary">
            {latestHealth?.db_size_mb ? `${latestHealth.db_size_mb} MB` : '—'}
          </p>
        </SpotlightCard>
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <Archive className="w-4 h-4 text-amber-400" />
            <span className="text-xs text-text-secondary">Retention Policies</span>
          </div>
          <p className="text-xl font-bold text-text-primary">{enforcedPolicies.length}</p>
          {totalOutsidePolicy > 0 && (
            <p className="text-[10px] text-amber-400">{totalOutsidePolicy} records outside policy</p>
          )}
        </SpotlightCard>
        <SpotlightCard className="p-4">
          <div className="flex items-center gap-2 mb-1">
            <Activity className="w-4 h-4 text-green-400" />
            <span className="text-xs text-text-secondary">Active Users (24h)</span>
          </div>
          <p className="text-xl font-bold text-text-primary">
            {latestHealth?.active_users_24h ?? '—'}
          </p>
        </SpotlightCard>
      </div>

      {/* Tab Bar */}
      <div className="flex gap-1 bg-white/5 rounded-lg p-1">
        {([
          { key: 'integrity' as Tab, label: 'Data Integrity' },
          { key: 'retention' as Tab, label: 'Retention Policies' },
          { key: 'health' as Tab, label: 'Health Logs' },
        ]).map(t => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={`flex-1 px-4 py-2 text-sm rounded-md transition-colors ${
              tab === t.key ? 'bg-white/10 text-text-primary' : 'text-text-secondary hover:text-text-primary'
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Integrity Checks */}
      {tab === 'integrity' && (
        <div className="space-y-2">
          {integrityChecks.length === 0 && (
            <p className="text-center text-text-secondary text-sm py-8">No integrity checks run yet. Click "Run Check" to start.</p>
          )}
          {integrityChecks.map(check => (
            <IntegrityCheckCard
              key={check.id}
              check={check}
              expanded={expandedCheck === check.id}
              onToggle={() => setExpandedCheck(prev => prev === check.id ? null : check.id)}
            />
          ))}
        </div>
      )}

      {/* Retention Policies */}
      {tab === 'retention' && (
        <div className="space-y-2">
          {retentionPolicies.map(policy => (
            <SpotlightCard key={policy.id} className="p-4">
              <div className="flex items-start justify-between">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-semibold text-text-primary">{policy.display_name}</h3>
                    {policy.is_enforced ? (
                      <span className="px-1.5 py-0.5 text-[10px] bg-green-500/20 text-green-300 rounded">ENFORCED</span>
                    ) : (
                      <span className="px-1.5 py-0.5 text-[10px] bg-white/5 text-text-secondary rounded">NOT ENFORCED</span>
                    )}
                  </div>
                  <p className="text-xs text-text-secondary mt-0.5">
                    {policy.retention_years} year{policy.retention_years !== 1 ? 's' : ''} · {policy.regulatory_basis}
                  </p>
                  {policy.description && <p className="text-xs text-text-secondary/70 mt-1">{policy.description}</p>}
                  <div className="flex items-center gap-4 mt-2">
                    <span className="text-xs text-text-secondary">
                      <span className="text-green-400">{policy.records_within_policy ?? 0}</span> within policy
                    </span>
                    {(policy.records_outside_policy ?? 0) > 0 && (
                      <span className="text-xs text-amber-400">
                        {policy.records_outside_policy} outside policy
                      </span>
                    )}
                    {policy.last_audit_at && (
                      <span className="text-xs text-text-secondary">
                        Audited {new Date(policy.last_audit_at).toLocaleDateString()}
                      </span>
                    )}
                  </div>
                </div>
                <button
                  onClick={() => updateRetentionPolicy(policy.id, { is_enforced: !policy.is_enforced })}
                  className={`px-2 py-1 text-xs rounded ${policy.is_enforced ? 'text-amber-400 hover:bg-amber-500/10' : 'text-green-400 hover:bg-green-500/10'}`}
                >
                  {policy.is_enforced ? 'Disable' : 'Enable'}
                </button>
              </div>
            </SpotlightCard>
          ))}
        </div>
      )}

      {/* Health Logs */}
      {tab === 'health' && (
        <div className="space-y-2">
          {healthLogs.length === 0 && (
            <p className="text-center text-text-secondary text-sm py-8">No health snapshots recorded yet.</p>
          )}
          {healthLogs.map(h => (
            <SpotlightCard key={h.id} className="p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Clock className="w-4 h-4 text-text-secondary" />
                  <span className="text-sm text-text-primary">{new Date(h.snapshot_at).toLocaleString()}</span>
                </div>
                <div className="flex items-center gap-4 text-xs text-text-secondary">
                  {h.db_size_mb != null && <span>DB: {h.db_size_mb} MB</span>}
                  {h.storage_usage_mb != null && <span>Storage: {h.storage_usage_mb} MB</span>}
                  {h.active_users_24h != null && <span>Users: {h.active_users_24h}</span>}
                  {h.error_count_24h != null && (
                    <span className={h.error_count_24h > 0 ? 'text-red-400' : ''}>
                      Errors: {h.error_count_24h}
                    </span>
                  )}
                  {h.avg_response_ms != null && <span>Avg: {h.avg_response_ms}ms</span>}
                </div>
              </div>
              {h.table_counts && Object.keys(h.table_counts).length > 0 && (
                <div className="mt-2 pt-2 border-t border-white/5 flex flex-wrap gap-3">
                  {Object.entries(h.table_counts).slice(0, 10).map(([table, count]) => (
                    <span key={table} className="text-[10px] text-text-secondary">
                      {table}: <span className="text-text-primary">{count}</span>
                    </span>
                  ))}
                </div>
              )}
            </SpotlightCard>
          ))}
        </div>
      )}
    </div>
  );
}

function IntegrityCheckCard({
  check, expanded, onToggle,
}: {
  check: DataIntegrityCheck;
  expanded: boolean;
  onToggle: () => void;
}) {
  const iconInfo = (STATUS_ICON[check.status] ?? STATUS_ICON.running)!;
  const Icon = iconInfo.icon;

  return (
    <SpotlightCard className="p-4">
      <button onClick={onToggle} className="w-full text-left">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Icon className={`w-5 h-5 ${iconInfo.color}`} />
            <div>
              <p className="text-sm font-semibold text-text-primary">
                {check.status.charAt(0).toUpperCase() + check.status.slice(1)}
                <span className="text-text-secondary font-normal ml-2">({check.run_type})</span>
              </p>
              <p className="text-xs text-text-secondary">
                {new Date(check.created_at).toLocaleString()}
                {check.duration_ms != null && ` · ${check.duration_ms}ms`}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3 text-xs">
            <span className="text-green-400">{check.checks_passed} pass</span>
            {check.checks_warned > 0 && <span className="text-amber-400">{check.checks_warned} warn</span>}
            {check.checks_failed > 0 && <span className="text-red-400">{check.checks_failed} fail</span>}
          </div>
        </div>
      </button>

      {expanded && check.results && check.results.length > 0 && (
        <div className="mt-3 pt-3 border-t border-white/5 space-y-1.5">
          {check.results.map((r: IntegrityCheckResult, i: number) => (
            <div key={i} className="flex items-center justify-between text-xs">
              <span className="text-text-secondary">{r.check}</span>
              <div className="flex items-center gap-2">
                {r.count > 0 && <span className="text-text-secondary">({r.count})</span>}
                <span className={CHECK_STATUS_COLOR[r.status] ?? 'text-text-secondary'}>
                  {r.status.toUpperCase()}
                </span>
              </div>
            </div>
          ))}
        </div>
      )}
    </SpotlightCard>
  );
}
