import { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { SpotlightCard } from '@/components/ui/SpotlightCard';
import { useWorkOrders } from '@/hooks/useWorkOrders';
import { useAuditLog } from '@/hooks/useAuditLog';
import {
  ClipboardList,
  Plus,
  Download,
  AlertTriangle,
  Clock,
  CheckCircle2,
  Wrench,
  User,
  Filter,
} from 'lucide-react';
import { clsx } from 'clsx';
import type { WorkOrderStatus, WorkOrderPriority, WorkOrderCategory } from '@/types/database';

const STATUS_LABELS: Record<WorkOrderStatus, string> = {
  open: 'Open',
  assigned: 'Assigned',
  in_progress: 'In Progress',
  completed: 'Completed',
  verified: 'Verified',
  cancelled: 'Cancelled',
};

const STATUS_COLORS: Record<WorkOrderStatus, string> = {
  open: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  assigned: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
  in_progress: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
  completed: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  verified: 'bg-green-500/20 text-green-300 border-green-500/30',
  cancelled: 'bg-gray-500/20 text-gray-400 border-gray-500/30',
};

const PRIORITY_COLORS: Record<WorkOrderPriority, string> = {
  low: 'bg-gray-500/20 text-gray-300',
  medium: 'bg-blue-500/20 text-blue-300',
  high: 'bg-amber-500/20 text-amber-300',
  critical: 'bg-red-500/20 text-red-300',
};

const CATEGORY_LABELS: Record<WorkOrderCategory, string> = {
  equipment_repair: 'Equipment Repair',
  erosion_control: 'Erosion Control',
  sediment_removal: 'Sediment Removal',
  outfall_maintenance: 'Outfall Maintenance',
  bmp_installation: 'BMP Installation',
  signage: 'Signage',
  access_road: 'Access Road',
  vegetation: 'Vegetation',
  structural: 'Structural',
  other: 'Other',
};

const DISCLAIMER = 'Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.';

export function WorkOrdersPage() {
  const { workOrders, loading, statusCounts, createWorkOrder } = useWorkOrders();
  const { log } = useAuditLog();
  const [statusFilter, setStatusFilter] = useState<WorkOrderStatus | 'all' | 'overdue'>('all');
  const [showCreate, setShowCreate] = useState(false);

  // Create form state
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [priority, setPriority] = useState<WorkOrderPriority>('medium');
  const [category, setCategory] = useState<WorkOrderCategory | ''>('');
  const [dueDate, setDueDate] = useState('');

  const filtered = useMemo(() => {
    if (statusFilter === 'all') return workOrders;
    if (statusFilter === 'overdue') {
      return workOrders.filter(
        (w) =>
          w.due_date &&
          new Date(w.due_date) < new Date() &&
          !['completed', 'verified', 'cancelled'].includes(w.status),
      );
    }
    return workOrders.filter((w) => w.status === statusFilter);
  }, [workOrders, statusFilter]);

  const handleCreate = async () => {
    if (!title.trim()) return;
    const result = await createWorkOrder({
      title: title.trim(),
      description: description.trim() || null,
      priority,
      category: (category as WorkOrderCategory) || null,
      due_date: dueDate || null,
      source_type: 'manual',
    });
    if (result) {
      setTitle('');
      setDescription('');
      setPriority('medium');
      setCategory('');
      setDueDate('');
      setShowCreate(false);
    }
  };

  const handleExport = () => {
    const headers = ['Title', 'Status', 'Priority', 'Category', 'Site', 'Assigned To', 'Due Date', 'Created'];
    const rows = filtered.map((w) => [
      w.title,
      w.status,
      w.priority,
      w.category ?? '',
      w.site_name ?? '',
      w.assigned_to_name ?? '',
      w.due_date ?? '',
      w.created_at.split('T')[0],
    ]);
    const csv = [headers, ...rows].map((r) => r.map((c) => `"${c}"`).join(',')).join('\n') + `\n\n"${DISCLAIMER}"`;
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `work_orders_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    log('work_order_export_csv', { count: filtered.length }, { module: 'work_orders', tableName: 'work_orders' });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-amber-500/20">
            <ClipboardList className="w-6 h-6 text-amber-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">Work Orders</h1>
            <p className="text-sm text-text-secondary">Deficiency tracking and SLA management</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-3 py-2 text-sm bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 text-text-secondary"
          >
            <Download className="w-4 h-4" />
            Export CSV
          </button>
          <button
            onClick={() => setShowCreate(!showCreate)}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium bg-amber-500/20 text-amber-300 border border-amber-500/30 rounded-lg hover:bg-amber-500/30"
          >
            <Plus className="w-4 h-4" />
            New Work Order
          </button>
        </div>
      </div>

      {/* Status Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3">
        {[
          { key: 'all' as const, label: 'All', count: workOrders.length, icon: ClipboardList, color: 'text-white' },
          { key: 'open' as const, label: 'Open', count: statusCounts.open, icon: Clock, color: 'text-blue-400' },
          { key: 'assigned' as const, label: 'Assigned', count: statusCounts.assigned, icon: User, color: 'text-amber-400' },
          { key: 'in_progress' as const, label: 'In Progress', count: statusCounts.in_progress, icon: Wrench, color: 'text-cyan-400' },
          { key: 'completed' as const, label: 'Completed', count: statusCounts.completed, icon: CheckCircle2, color: 'text-emerald-400' },
          { key: 'verified' as const, label: 'Verified', count: statusCounts.verified, icon: CheckCircle2, color: 'text-green-400' },
          { key: 'overdue' as const, label: 'Overdue', count: statusCounts.overdue, icon: AlertTriangle, color: 'text-red-400' },
        ].map(({ key, label, count, icon: Icon, color }) => (
          <button
            key={key}
            onClick={() => setStatusFilter(key)}
            className={clsx(
              'p-3 rounded-lg border text-left transition-all',
              statusFilter === key
                ? 'bg-white/10 border-white/20'
                : 'bg-white/[0.02] border-white/5 hover:bg-white/5',
            )}
          >
            <Icon className={clsx('w-4 h-4 mb-1', color)} />
            <div className="text-xl font-bold text-white">{count}</div>
            <div className="text-xs text-text-secondary">{label}</div>
          </button>
        ))}
      </div>

      {/* Create Form */}
      {showCreate && (
        <SpotlightCard className="p-6 space-y-4">
          <h3 className="text-lg font-semibold text-white">New Work Order</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="md:col-span-2">
              <label className="block text-sm text-text-secondary mb-1">Title *</label>
              <input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder:text-text-secondary focus:border-amber-500/50 focus:outline-none"
                placeholder="Describe the work needed..."
              />
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm text-text-secondary mb-1">Description</label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={3}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder:text-text-secondary focus:border-amber-500/50 focus:outline-none resize-none"
                placeholder="Additional details..."
              />
            </div>
            <div>
              <label className="block text-sm text-text-secondary mb-1">Priority</label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value as WorkOrderPriority)}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:border-amber-500/50 focus:outline-none"
              >
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="critical">Critical</option>
              </select>
            </div>
            <div>
              <label className="block text-sm text-text-secondary mb-1">Category</label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value as WorkOrderCategory)}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:border-amber-500/50 focus:outline-none"
              >
                <option value="">Select category...</option>
                {Object.entries(CATEGORY_LABELS).map(([k, v]) => (
                  <option key={k} value={k}>{v}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm text-text-secondary mb-1">Due Date</label>
              <input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white focus:border-amber-500/50 focus:outline-none"
              />
            </div>
          </div>
          <div className="flex justify-end gap-2">
            <button
              onClick={() => setShowCreate(false)}
              className="px-4 py-2 text-sm text-text-secondary hover:text-white"
            >
              Cancel
            </button>
            <button
              onClick={handleCreate}
              disabled={!title.trim()}
              className="px-4 py-2 text-sm font-medium bg-amber-500/20 text-amber-300 border border-amber-500/30 rounded-lg hover:bg-amber-500/30 disabled:opacity-40"
            >
              Create Work Order
            </button>
          </div>
        </SpotlightCard>
      )}

      {/* Work Orders List */}
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin h-8 w-8 border-2 border-amber-400 border-t-transparent rounded-full" />
        </div>
      ) : filtered.length === 0 ? (
        <SpotlightCard className="p-12 text-center">
          <Filter className="w-8 h-8 text-text-secondary mx-auto mb-3" />
          <p className="text-text-secondary">No work orders found</p>
        </SpotlightCard>
      ) : (
        <div className="space-y-2">
          {filtered.map((wo) => {
            const isOverdue =
              wo.due_date &&
              new Date(wo.due_date) < new Date() &&
              !['completed', 'verified', 'cancelled'].includes(wo.status);

            return (
              <Link key={wo.id} to={`/work-orders/${wo.id}`}>
                <SpotlightCard className="p-4 hover:bg-white/[0.04] transition-colors">
                  <div className="flex items-center justify-between">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="text-white font-medium truncate">{wo.title}</h3>
                        {isOverdue && (
                          <span className="flex items-center gap-1 text-xs text-red-400">
                            <AlertTriangle className="w-3 h-3" />
                            Overdue
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-3 text-xs text-text-secondary">
                        {wo.site_name && <span>{wo.site_name}</span>}
                        {wo.category && <span>{CATEGORY_LABELS[wo.category]}</span>}
                        {wo.assigned_to_name && (
                          <span className="flex items-center gap-1">
                            <User className="w-3 h-3" />
                            {wo.assigned_to_name}
                          </span>
                        )}
                        {wo.due_date && (
                          <span className={clsx(isOverdue && 'text-red-400')}>
                            Due: {wo.due_date}
                          </span>
                        )}
                        <span>{wo.created_at.split('T')[0]}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 ml-4">
                      <span className={clsx('px-2 py-0.5 rounded text-xs font-medium', PRIORITY_COLORS[wo.priority])}>
                        {wo.priority}
                      </span>
                      <span className={clsx('px-2 py-0.5 rounded text-xs font-medium border', STATUS_COLORS[wo.status])}>
                        {STATUS_LABELS[wo.status]}
                      </span>
                    </div>
                  </div>
                </SpotlightCard>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}

export default WorkOrdersPage;
