// =============================================================================
// generate-report — Report Generation Edge Function for SCC CMS
// Generates CSV reports from real database data, uploads to Storage,
// tracks job status in generated_reports table.
// =============================================================================

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

// ── Constants ────────────────────────────────────────────────────────────────
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ALLOWED_ORIGIN = Deno.env.get("FRONTEND_URL") ?? "http://localhost:5173";
const MAX_ROWS = 10_000;
const DISCLAIMER =
  "Generated by SCC Compliance Monitor — a compliance reporting tool. Not an EMS. Not legal or environmental consulting. All data and reports require independent verification by qualified personnel before regulatory submission.";

// ── Types ────────────────────────────────────────────────────────────────────
type SB = ReturnType<typeof createClient>;
interface Auth {
  userId: string;
  orgId: string;
}
interface Config {
  date_from?: string;
  date_to?: string;
  states?: string[];
  org_ids?: string[];
}
interface Result {
  columns: string[];
  rows: unknown[][];
  flags: Record<string, unknown>;
}
type ReportFn = (sb: SB, orgIds: string[], cfg: Config) => Promise<Result>;

// ── CORS ─────────────────────────────────────────────────────────────────────
const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

function json(body: Record<string, unknown>, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// ── Auth ─────────────────────────────────────────────────────────────────────
async function authenticate(req: Request, sb: SB): Promise<Auth | null> {
  const hdr = req.headers.get("Authorization");
  if (!hdr?.startsWith("Bearer ")) return null;
  const {
    data: { user },
    error,
  } = await sb.auth.getUser(hdr.replace("Bearer ", ""));
  if (error || !user) return null;

  const { data: profile } = await sb
    .from("user_profiles")
    .select("id, organization_id")
    .eq("id", user.id)
    .single();
  if (!profile) return null;

  return {
    userId: user.id,
    orgId: profile.organization_id as string,
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────
async function getVisibleOrgIds(sb: SB, userOrgId: string): Promise<string[]> {
  const { data: orgs } = await sb
    .from("organizations")
    .select("id, parent_id")
    .eq("is_active", true);
  if (!orgs) return [userOrgId];

  const userOrg = orgs.find((o: Record<string, unknown>) => o.id === userOrgId);
  if (!userOrg) return [userOrgId];

  const parentId = userOrg.parent_id as string | null;
  return orgs
    .filter(
      (o: Record<string, unknown>) =>
        o.id === userOrgId ||
        o.parent_id === userOrgId ||
        (parentId && (o.id === parentId || o.parent_id === parentId)),
    )
    .map((o: Record<string, unknown>) => o.id as string);
}

async function getSiteIds(sb: SB, orgIds: string[]): Promise<string[]> {
  const { data } = await sb
    .from("sites")
    .select("id")
    .in("organization_id", orgIds);
  return (data ?? []).map((s: Record<string, unknown>) => s.id as string);
}

function ninetyDaysAgo(): string {
  const d = new Date();
  d.setDate(d.getDate() - 90);
  return d.toISOString().split("T")[0];
}

const CSV_INJECTION_RE = /^[=+\-@\t\r]/;

function escapeCsv(v: unknown): string {
  if (v === null || v === undefined) return "";
  let s = String(v);
  // Neutralize CSV formula injection (=, +, -, @, tab, cr)
  if (CSV_INJECTION_RE.test(s)) {
    s = `'${s}`;
  }
  return s.includes(",") || s.includes('"') || s.includes("\n") || s.includes("'")
    ? `"${s.replace(/"/g, '""')}"`
    : s;
}

function toCsv(columns: string[], rows: unknown[][]): string {
  const header = columns.map(escapeCsv).join(",");
  const body = rows.map((r) => r.map(escapeCsv).join(",")).join("\n");
  return `${header}\n${body}\n\n"${DISCLAIMER}"`;
}

function makeFlags(rows: unknown[][]): Record<string, unknown> {
  const flags: Record<string, unknown> = {};
  if (rows.length >= MAX_ROWS) flags.row_limit_hit = true;
  return flags;
}

// ── Input Validation ────────────────────────────────────────────────────────
const VALID_STATES = new Set(["AL", "KY", "TN", "VA", "WV"]);
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const ALLOWED_FORMATS = new Set(["csv"]);

function sanitizeConfig(cfg: Config): Config {
  const clean: Config = {};
  if (cfg.date_from && typeof cfg.date_from === "string" && ISO_DATE_RE.test(cfg.date_from) && !isNaN(Date.parse(cfg.date_from))) {
    clean.date_from = cfg.date_from;
  }
  if (cfg.date_to && typeof cfg.date_to === "string" && ISO_DATE_RE.test(cfg.date_to) && !isNaN(Date.parse(cfg.date_to))) {
    clean.date_to = cfg.date_to;
  }
  if (Array.isArray(cfg.states)) {
    clean.states = cfg.states
      .filter((s): s is string => typeof s === "string" && VALID_STATES.has(s.toUpperCase()))
      .map((s) => s.toUpperCase());
  }
  if (Array.isArray(cfg.org_ids)) {
    clean.org_ids = cfg.org_ids.filter(
      (id): id is string => typeof id === "string" && UUID_RE.test(id),
    );
  }
  return clean;
}

// ── Report #1: Permit Inventory ──────────────────────────────────────────────
async function rptPermitInventory(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  const { data, error } = await sb
    .from("npdes_permits")
    .select(
      `permit_number, permit_type, status, issued_date, effective_date,
       expiration_date, issuing_agency, facility_name, permittee_name,
       sites(name, city, county, states(code)),
       organizations(name)`,
    )
    .in("organization_id", orgIds)
    .order("permit_number")
    .limit(MAX_ROWS);
  if (error) throw new Error(error.message);

  const columns = [
    "Permit Number", "Type", "Status", "Issued", "Effective", "Expiration",
    "Agency", "Facility", "Permittee", "Site", "City", "County", "State",
    "Organization",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => {
    const site = r.sites as Record<string, unknown> | null;
    const state = site?.states as Record<string, unknown> | null;
    const org = r.organizations as Record<string, unknown> | null;
    return [
      r.permit_number, r.permit_type, r.status, r.issued_date,
      r.effective_date, r.expiration_date, r.issuing_agency, r.facility_name,
      r.permittee_name, site?.name, site?.city, site?.county, state?.code,
      org?.name,
    ];
  });
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #2: Permit Renewal Tracker ────────────────────────────────────────
async function rptPermitRenewalTracker(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  const { data, error } = await sb
    .from("npdes_permits")
    .select(
      `permit_number, status, effective_date, expiration_date,
       administratively_continued, facility_name,
       sites(name, states(code)), organizations(name)`,
    )
    .in("organization_id", orgIds)
    .order("expiration_date")
    .limit(MAX_ROWS);
  if (error) throw new Error(error.message);

  const today = new Date();
  const columns = [
    "Permit Number", "Status", "Effective", "Expiration",
    "Days Until Expiration", "Admin Continued", "Facility", "Site", "State",
    "Organization",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => {
    const site = r.sites as Record<string, unknown> | null;
    const state = site?.states as Record<string, unknown> | null;
    const org = r.organizations as Record<string, unknown> | null;
    const exp = r.expiration_date ? new Date(r.expiration_date as string) : null;
    const daysUntil = exp
      ? Math.round((exp.getTime() - today.getTime()) / 86_400_000)
      : null;
    return [
      r.permit_number, r.status, r.effective_date, r.expiration_date,
      daysUntil, r.administratively_continued ? "Yes" : "No", r.facility_name,
      site?.name, state?.code, org?.name,
    ];
  });
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #3: Outfall Inventory ─────────────────────────────────────────────
async function rptOutfallInventory(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  const siteIds = await getSiteIds(sb, orgIds);
  if (!siteIds.length) return { columns: [], rows: [], flags: {} };

  const { data, error } = await sb
    .from("outfalls")
    .select(
      `outfall_number, description, outfall_type, receiving_water,
       latitude, longitude, is_active, dsn, drainage_area_acres,
       sites(name, states(code)), npdes_permits(permit_number)`,
    )
    .in("site_id", siteIds)
    .order("outfall_number")
    .limit(MAX_ROWS);
  if (error) throw new Error(error.message);

  const columns = [
    "Outfall", "Description", "Type", "Receiving Water", "Latitude",
    "Longitude", "Active", "DSN", "Drainage Area (acres)", "Site",
    "State", "Permit Number",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => {
    const site = r.sites as Record<string, unknown> | null;
    const state = site?.states as Record<string, unknown> | null;
    const permit = r.npdes_permits as Record<string, unknown> | null;
    return [
      r.outfall_number, r.description, r.outfall_type, r.receiving_water,
      r.latitude, r.longitude, r.is_active ? "Yes" : "No", r.dsn,
      r.drainage_area_acres, site?.name, state?.code, permit?.permit_number,
    ];
  });
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #4: Permit Limit Parameter Matrix ─────────────────────────────────
async function rptPermitLimitMatrix(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  // 2-query approach: get permit IDs for visible orgs, then limits
  const { data: permits } = await sb
    .from("npdes_permits")
    .select("id, permit_number")
    .in("organization_id", orgIds);
  const permitMap = new Map(
    (permits ?? []).map((p: Record<string, unknown>) => [p.id, p.permit_number]),
  );
  const permitIds = [...permitMap.keys()] as string[];
  if (!permitIds.length) return { columns: [], rows: [], flags: {} };

  const { data, error } = await sb
    .from("permit_limits")
    .select(
      `permit_id, storet_code, limit_type, limit_value, unit,
       statistical_base, monitoring_frequency, sample_type,
       effective_date, end_date, review_status,
       outfalls(outfall_number)`,
    )
    .in("permit_id", permitIds)
    .order("storet_code")
    .limit(MAX_ROWS);
  if (error) throw new Error(error.message);

  const columns = [
    "Permit Number", "Outfall", "STORET Code", "Limit Type", "Limit Value",
    "Unit", "Statistical Base", "Monitoring Frequency", "Sample Type",
    "Effective", "End Date", "Review Status",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => {
    const outfall = r.outfalls as Record<string, unknown> | null;
    return [
      permitMap.get(r.permit_id as string) ?? "", outfall?.outfall_number,
      r.storet_code, r.limit_type, r.limit_value, r.unit, r.statistical_base,
      r.monitoring_frequency, r.sample_type, r.effective_date, r.end_date,
      r.review_status,
    ];
  });
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #5: EPA ECHO Noncompliance ────────────────────────────────────────
async function rptEchoNoncompliance(
  sb: SB,
  orgIds: string[],
  cfg: Config,
): Promise<Result> {
  let query = sb
    .from("external_echo_dmrs")
    .select(
      `npdes_id, outfall, monitoring_period_start, monitoring_period_end,
       parameter_desc, statistical_base, limit_value, limit_unit,
       dmr_value, dmr_unit, violation_code, violation_desc, exceedance_pct`,
    )
    .in("organization_id", orgIds)
    .not("violation_code", "is", null)
    .order("monitoring_period_end", { ascending: false })
    .limit(MAX_ROWS);

  if (cfg.date_from) query = query.gte("monitoring_period_start", cfg.date_from);
  if (cfg.date_to) query = query.lte("monitoring_period_end", cfg.date_to);

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  const columns = [
    "NPDES ID", "Outfall", "Period Start", "Period End", "Parameter",
    "Stat Base", "Limit", "Limit Unit", "DMR Value", "DMR Unit",
    "Violation Code", "Violation Description", "Exceedance %",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.npdes_id, r.outfall, r.monitoring_period_start, r.monitoring_period_end,
    r.parameter_desc, r.statistical_base, r.limit_value, r.limit_unit,
    r.dmr_value, r.dmr_unit, r.violation_code, r.violation_desc,
    r.exceedance_pct,
  ]);
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #6: EPA DMR Data Summary ──────────────────────────────────────────
async function rptEchoDmrSummary(
  sb: SB,
  orgIds: string[],
  cfg: Config,
): Promise<Result> {
  const dateFrom = cfg.date_from ?? ninetyDaysAgo();
  let query = sb
    .from("external_echo_dmrs")
    .select(
      `npdes_id, outfall, monitoring_period_start, monitoring_period_end,
       parameter_code, parameter_desc, statistical_base, limit_value,
       limit_unit, dmr_value, dmr_unit, nodi_code, violation_code`,
    )
    .in("organization_id", orgIds)
    .gte("monitoring_period_start", dateFrom)
    .order("monitoring_period_end", { ascending: false })
    .limit(MAX_ROWS);

  if (cfg.date_to) query = query.lte("monitoring_period_end", cfg.date_to);

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  const columns = [
    "NPDES ID", "Outfall", "Period Start", "Period End", "Param Code",
    "Parameter", "Stat Base", "Limit", "Limit Unit", "DMR Value",
    "DMR Unit", "NODI Code", "Violation Code",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.npdes_id, r.outfall, r.monitoring_period_start, r.monitoring_period_end,
    r.parameter_code, r.parameter_desc, r.statistical_base, r.limit_value,
    r.limit_unit, r.dmr_value, r.dmr_unit, r.nodi_code, r.violation_code,
  ]);

  const flags = makeFlags(rows);
  flags.date_filter_applied = true;
  if (!cfg.date_from) flags.default_date_range = "Last 90 days";
  return { columns, rows, flags };
}

// ── Report #7: Consent Decree Obligations ────────────────────────────────────
// SYSTEM-WIDE: Single Consent Decree (Case 7:16-cv-00462-GEC) applies to SCC
// parent + all 26 subsidiaries. No org filter needed. If multi-tenant beyond
// SCC is added, this table MUST be org-scoped.
async function rptConsentDecree(
  sb: SB,
  _orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  const { data, error } = await sb
    .from("consent_decree_obligations")
    .select(
      `paragraph_number, title, obligation_type, frequency, status,
       initial_due_date, next_due_date, completion_date,
       responsible_role, days_at_risk, penalty_tier, accrued_penalty, notes`,
    )
    .order("paragraph_number")
    .limit(MAX_ROWS);
  if (error) throw new Error(error.message);

  const columns = [
    "Paragraph", "Title", "Type", "Frequency", "Status", "Initial Due",
    "Next Due", "Completed", "Responsible Role", "Days at Risk",
    "Penalty Tier", "Accrued Penalty", "Notes",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.paragraph_number, r.title, r.obligation_type, r.frequency, r.status,
    r.initial_due_date, r.next_due_date, r.completion_date,
    r.responsible_role, r.days_at_risk, r.penalty_tier, r.accrued_penalty,
    r.notes,
  ]);
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #8: FTS Violation Report ──────────────────────────────────────────
async function rptFtsViolations(
  sb: SB,
  orgIds: string[],
  cfg: Config,
): Promise<Result> {
  let query = sb
    .from("fts_violations")
    .select(
      `monitoring_year, monitoring_month, monitoring_quarter, state,
       dnr_number, outfall_number, penalty_category, penalty_amount, notes`,
    )
    .in("organization_id", orgIds)
    .order("monitoring_year", { ascending: false })
    .limit(MAX_ROWS);

  if (cfg.states?.length) query = query.in("state", cfg.states);

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  const columns = [
    "Year", "Month", "Quarter", "State", "DNR Number", "Outfall",
    "Penalty Category", "Penalty Amount", "Notes",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.monitoring_year, r.monitoring_month, r.monitoring_quarter, r.state,
    r.dnr_number, r.outfall_number, r.penalty_category, r.penalty_amount,
    r.notes,
  ]);
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #9: Discrepancy Triage ────────────────────────────────────────────
async function rptDiscrepancyTriage(
  sb: SB,
  orgIds: string[],
  cfg: Config,
): Promise<Result> {
  const dateFrom = cfg.date_from ?? ninetyDaysAgo();
  let query = sb
    .from("discrepancy_reviews")
    .select(
      `npdes_id, discrepancy_type, severity, status, source,
       monitoring_period_start, monitoring_period_end, description,
       internal_value, external_value, detected_at, resolved_at,
       recurrence_count`,
    )
    .in("organization_id", orgIds)
    .gte("detected_at", dateFrom)
    .order("detected_at", { ascending: false })
    .limit(MAX_ROWS);

  if (cfg.date_to) query = query.lte("detected_at", cfg.date_to);

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  const columns = [
    "NPDES ID", "Type", "Severity", "Status", "Source", "Period Start",
    "Period End", "Description", "Internal Value", "External Value",
    "Detected", "Resolved", "Recurrence Count",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.npdes_id, r.discrepancy_type, r.severity, r.status, r.source,
    r.monitoring_period_start, r.monitoring_period_end, r.description,
    r.internal_value, r.external_value, r.detected_at, r.resolved_at,
    r.recurrence_count,
  ]);

  const flags = makeFlags(rows);
  flags.date_filter_applied = true;
  return { columns, rows, flags };
}

// ── Report #10: AI Extraction Verification ───────────────────────────────────
async function rptAiVerification(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  const { data, error } = await sb
    .from("file_processing_queue")
    .select(
      `file_name, file_category, state_code, status,
       records_extracted, records_imported, records_failed,
       created_at, processing_completed_at`,
    )
    .in("organization_id", orgIds)
    .order("created_at", { ascending: false })
    .limit(MAX_ROWS);
  if (error) throw new Error(error.message);

  const columns = [
    "File Name", "Category", "State", "Status", "Records Extracted",
    "Records Imported", "Records Failed", "Uploaded", "Completed",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.file_name, r.file_category, r.state_code, r.status,
    r.records_extracted, r.records_imported, r.records_failed,
    r.created_at, r.processing_completed_at,
  ]);
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #11: System Audit Trail ───────────────────────────────────────────
async function rptAuditTrail(
  sb: SB,
  orgIds: string[],
  cfg: Config,
): Promise<Result> {
  const dateFrom = cfg.date_from ?? ninetyDaysAgo();
  let query = sb
    .from("audit_log")
    .select(
      `action, module, table_name, record_id, description,
       user_id, created_at`,
    )
    .in("organization_id", orgIds)
    .gte("created_at", dateFrom)
    .order("created_at", { ascending: false })
    .limit(MAX_ROWS);

  if (cfg.date_to) query = query.lte("created_at", cfg.date_to);

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  const columns = [
    "Action", "Module", "Table", "Record ID", "Description", "User ID",
    "Timestamp",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.action, r.module, r.table_name, r.record_id, r.description,
    r.user_id, r.created_at,
  ]);

  const flags = makeFlags(rows);
  flags.date_filter_applied = true;
  return { columns, rows, flags };
}

// ── Report #12: File Processing Pipeline ─────────────────────────────────────
async function rptFilePipeline(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  const { data, error } = await sb
    .from("file_processing_queue")
    .select(
      `file_name, file_category, state_code, status, mime_type,
       file_size_bytes, processing_started_at, processing_completed_at,
       records_extracted, records_imported, records_failed,
       r2_archived, created_at`,
    )
    .in("organization_id", orgIds)
    .order("created_at", { ascending: false })
    .limit(MAX_ROWS);
  if (error) throw new Error(error.message);

  const columns = [
    "File Name", "Category", "State", "Status", "MIME Type", "Size (bytes)",
    "Processing Started", "Processing Completed", "Records Extracted",
    "Records Imported", "Records Failed", "R2 Archived", "Uploaded",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.file_name, r.file_category, r.state_code, r.status, r.mime_type,
    r.file_size_bytes, r.processing_started_at, r.processing_completed_at,
    r.records_extracted, r.records_imported, r.records_failed,
    r.r2_archived ? "Yes" : "No", r.created_at,
  ]);
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #13: Regulatory Deadline Tracker ──────────────────────────────────
// SYSTEM-WIDE: regulatory_deadlines is shared reference data across all states.
// Filtered by state only, not org. If multi-tenant beyond SCC is added, scope.
async function rptRegulatoryDeadlines(
  sb: SB,
  _orgIds: string[],
  cfg: Config,
): Promise<Result> {
  let query = sb
    .from("regulatory_deadlines")
    .select(
      `deadline_type, description, reference_event, offset_days,
       offset_hours, day_of_month, form_number, submission_method,
       states(code, name)`,
    )
    .order("deadline_type")
    .limit(MAX_ROWS);

  // state filter uses state_id FK — resolve codes to IDs
  if (cfg.states?.length) {
    const { data: stateRows } = await sb
      .from("states")
      .select("id")
      .in("code", cfg.states);
    const stateIds = (stateRows ?? []).map(
      (s: Record<string, unknown>) => s.id as string,
    );
    if (stateIds.length) query = query.in("state_id", stateIds);
  }

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  const columns = [
    "Deadline Type", "Description", "Reference Event", "Offset Days",
    "Offset Hours", "Day of Month", "Form Number", "Submission Method",
    "State Code", "State Name",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => {
    const state = r.states as Record<string, unknown> | null;
    return [
      r.deadline_type, r.description, r.reference_event, r.offset_days,
      r.offset_hours, r.day_of_month, r.form_number, r.submission_method,
      state?.code, state?.name,
    ];
  });
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #14: State Compliance Matrix ──────────────────────────────────────
async function rptStateComplianceMatrix(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  // Aggregate permits per state
  const { data: permits } = await sb
    .from("npdes_permits")
    .select("id, status, sites(states(code))")
    .in("organization_id", orgIds);

  // Aggregate noncompliance from ECHO
  const { data: echoFacilities } = await sb
    .from("external_echo_facilities")
    .select("npdes_id, state_code, compliance_status, qtrs_in_nc")
    .in("organization_id", orgIds);

  // State configs
  const { data: stateConfigs } = await sb
    .from("state_regulatory_configs")
    .select("issuing_agency_name, dmr_submission_system, states(code, name)");

  // Build state map
  const stateMap = new Map<
    string,
    {
      name: string;
      agency: string;
      dmrSystem: string;
      totalPermits: number;
      activePermits: number;
      facilitiesInNC: number;
      maxQtrsNC: number;
    }
  >();

  for (const sc of stateConfigs ?? []) {
    const st = (sc as Record<string, unknown>).states as Record<string, unknown> | null;
    if (!st?.code) continue;
    const code = st.code as string;
    stateMap.set(code, {
      name: st.name as string,
      agency: (sc as Record<string, unknown>).issuing_agency_name as string,
      dmrSystem: (sc as Record<string, unknown>).dmr_submission_system as string,
      totalPermits: 0,
      activePermits: 0,
      facilitiesInNC: 0,
      maxQtrsNC: 0,
    });
  }

  for (const p of permits ?? []) {
    const site = (p as Record<string, unknown>).sites as Record<string, unknown> | null;
    const state = site?.states as Record<string, unknown> | null;
    const code = state?.code as string;
    if (!code || !stateMap.has(code)) continue;
    const entry = stateMap.get(code)!;
    entry.totalPermits++;
    if ((p as Record<string, unknown>).status === "active") entry.activePermits++;
  }

  for (const f of echoFacilities ?? []) {
    const row = f as Record<string, unknown>;
    const code = row.state_code as string;
    if (!code || !stateMap.has(code)) continue;
    const entry = stateMap.get(code)!;
    if (row.compliance_status !== "No Violation") entry.facilitiesInNC++;
    const qtrs = (row.qtrs_in_nc as number) ?? 0;
    if (qtrs > entry.maxQtrsNC) entry.maxQtrsNC = qtrs;
  }

  const columns = [
    "State", "State Name", "Agency", "DMR System", "Total Permits",
    "Active Permits", "Facilities in Noncompliance", "Max Quarters in NC",
  ];
  const rows = [...stateMap.entries()].map(([code, e]) => [
    code, e.name, e.agency, e.dmrSystem, e.totalPermits, e.activePermits,
    e.facilitiesInNC, e.maxQtrsNC,
  ]);
  return { columns, rows, flags: {} };
}

// ── Report #15: External Sync Health ─────────────────────────────────────────
async function rptSyncHealth(
  sb: SB,
  orgIds: string[],
  cfg: Config,
): Promise<Result> {
  let query = sb
    .from("external_sync_log")
    .select(
      `source, sync_type, status, started_at, completed_at,
       records_synced, records_failed, created_at`,
    )
    .in("organization_id", orgIds)
    .order("created_at", { ascending: false })
    .limit(MAX_ROWS);

  if (cfg.date_from) query = query.gte("created_at", cfg.date_from);
  if (cfg.date_to) query = query.lte("created_at", cfg.date_to);

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  const columns = [
    "Source", "Sync Type", "Status", "Started", "Completed",
    "Records Synced", "Records Failed", "Created",
  ];
  const rows = (data ?? []).map((r: Record<string, unknown>) => [
    r.source, r.sync_type, r.status, r.started_at, r.completed_at,
    r.records_synced, r.records_failed, r.created_at,
  ]);
  return { columns, rows, flags: makeFlags(rows) };
}

// ── Report #27: Executive Dashboard Summary ──────────────────────────────────
async function rptExecutiveSummary(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  // Aggregate key metrics across the system
  const [permitsRes, echoRes, ftsRes, obligationsRes, syncRes] =
    await Promise.all([
      sb
        .from("npdes_permits")
        .select("id, status", { count: "exact", head: false })
        .in("organization_id", orgIds),
      sb
        .from("external_echo_dmrs")
        .select("id, violation_code", { count: "exact", head: false })
        .in("organization_id", orgIds)
        .not("violation_code", "is", null),
      sb
        .from("fts_violations")
        .select("id", { count: "exact", head: false })
        .in("organization_id", orgIds),
      sb.from("consent_decree_obligations").select("id, status"),
      sb
        .from("external_sync_log")
        .select("id, status")
        .in("organization_id", orgIds)
        .order("created_at", { ascending: false })
        .limit(10),
    ]);

  const totalPermits = permitsRes.data?.length ?? 0;
  const activePermits = (permitsRes.data ?? []).filter(
    (p: Record<string, unknown>) => p.status === "active",
  ).length;
  const echoViolations = echoRes.data?.length ?? 0;
  const ftsViolations = ftsRes.data?.length ?? 0;

  const obligations = obligationsRes.data ?? [];
  const obligComplete = obligations.filter(
    (o: Record<string, unknown>) => o.status === "complete",
  ).length;
  const obligOverdue = obligations.filter(
    (o: Record<string, unknown>) => o.status === "overdue",
  ).length;

  const recentSyncs = syncRes.data ?? [];
  const syncFailures = recentSyncs.filter(
    (s: Record<string, unknown>) => s.status === "failed",
  ).length;

  const columns = ["Metric", "Value"];
  const rows = [
    ["Total Permits", totalPermits],
    ["Active Permits", activePermits],
    ["ECHO Violations (all time)", echoViolations],
    ["FTS Violations (all time)", ftsViolations],
    ["Consent Decree Obligations", obligations.length],
    ["Obligations Complete", obligComplete],
    ["Obligations Overdue", obligOverdue],
    ["Recent Sync Failures (last 10)", syncFailures],
    ["Report Generated", new Date().toISOString()],
  ];
  return { columns, rows, flags: {} };
}

// ── Report #28: Inspection Prep Package ──────────────────────────────────────
async function rptInspectionPrep(
  sb: SB,
  orgIds: string[],
  _cfg: Config,
): Promise<Result> {
  // Comprehensive snapshot for inspection readiness
  const [permitsRes, outfallsRes, echoRes, obligationsRes] = await Promise.all([
    sb
      .from("npdes_permits")
      .select(
        `permit_number, status, effective_date, expiration_date,
         facility_name, sites(name, city, county, states(code))`,
      )
      .in("organization_id", orgIds)
      .limit(500),
    sb
      .from("outfalls")
      .select("outfall_number, outfall_type, receiving_water, is_active, sites(name)")
      .in(
        "site_id",
        (await getSiteIds(sb, orgIds)),
      )
      .limit(1000),
    sb
      .from("external_echo_facilities")
      .select(
        "npdes_id, facility_name, compliance_status, qtrs_in_nc, last_inspection_date",
      )
      .in("organization_id", orgIds),
    sb
      .from("consent_decree_obligations")
      .select("paragraph_number, title, status, next_due_date")
      .in("status", ["overdue", "at_risk", "pending"]),
  ]);

  // Flatten into a multi-section report
  const columns = [
    "Section", "Item", "Detail 1", "Detail 2", "Detail 3", "Status",
  ];
  const rows: unknown[][] = [];

  // Section 1: Permits
  for (const p of permitsRes.data ?? []) {
    const r = p as Record<string, unknown>;
    const site = r.sites as Record<string, unknown> | null;
    const state = site?.states as Record<string, unknown> | null;
    rows.push([
      "Permits", r.permit_number, r.facility_name, state?.code,
      `Expires: ${r.expiration_date ?? "N/A"}`, r.status,
    ]);
  }

  // Section 2: ECHO Compliance Status
  for (const f of echoRes.data ?? []) {
    const r = f as Record<string, unknown>;
    rows.push([
      "ECHO Compliance", r.npdes_id, r.facility_name,
      `Last Inspection: ${r.last_inspection_date ?? "N/A"}`,
      `Qtrs in NC: ${r.qtrs_in_nc ?? 0}`, r.compliance_status,
    ]);
  }

  // Section 3: Active Outfalls
  const activeOutfalls = (outfallsRes.data ?? []).filter(
    (o: Record<string, unknown>) => o.is_active,
  );
  rows.push([
    "Outfalls", `Total Active: ${activeOutfalls.length}`, "", "", "", "",
  ]);

  // Section 4: Pending Obligations
  for (const o of obligationsRes.data ?? []) {
    const r = o as Record<string, unknown>;
    rows.push([
      "Obligations", r.paragraph_number, r.title, `Due: ${r.next_due_date ?? "N/A"}`,
      "", r.status,
    ]);
  }

  return { columns, rows, flags: {} };
}

// ── Report Registry ──────────────────────────────────────────────────────────
const REGISTRY: Record<string, ReportFn> = {
  permit_inventory: rptPermitInventory,
  permit_renewal_tracker: rptPermitRenewalTracker,
  outfall_inventory: rptOutfallInventory,
  permit_limit_parameter_matrix: rptPermitLimitMatrix,
  epa_echo_noncompliance: rptEchoNoncompliance,
  epa_dmr_data_summary: rptEchoDmrSummary,
  consent_decree_obligations: rptConsentDecree,
  fts_violation_report: rptFtsViolations,
  discrepancy_triage: rptDiscrepancyTriage,
  ai_extraction_verification: rptAiVerification,
  system_audit_trail: rptAuditTrail,
  file_processing_pipeline: rptFilePipeline,
  regulatory_deadline_tracker: rptRegulatoryDeadlines,
  state_compliance_matrix: rptStateComplianceMatrix,
  external_sync_health: rptSyncHealth,
  executive_dashboard_summary: rptExecutiveSummary,
  inspection_prep_package: rptInspectionPrep,
};

// ── Main Handler ─────────────────────────────────────────────────────────────
Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  if (req.method !== "POST") {
    return json({ error: "Method not allowed" }, 405);
  }

  const sb = createClient(SUPABASE_URL, SERVICE_KEY);

  // 1. Authenticate
  const auth = await authenticate(req, sb);
  if (!auth) return json({ error: "Unauthorized" }, 401);

  // 2. Parse body
  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return json({ error: "Invalid JSON body" }, 400);
  }

  const reportKey = body.report_key as string;
  const format = ALLOWED_FORMATS.has(body.format as string) ? (body.format as string) : "csv";
  const config = sanitizeConfig((body.config as Config) ?? {});

  if (!reportKey || typeof reportKey !== "string") {
    return json({ error: "report_key required" }, 400);
  }

  // 3. Validate report definition
  const { data: reportDef } = await sb
    .from("report_definitions")
    .select("id, report_key, report_number, title, is_locked")
    .eq("report_key", reportKey)
    .single();

  if (!reportDef) return json({ error: "Unknown report key" }, 400);
  if (reportDef.is_locked) {
    return json(
      { error: "Report unavailable — prerequisite data not yet uploaded" },
      400,
    );
  }

  // 4. Check permission
  const { data: roleAssignments } = await sb
    .from("user_role_assignments")
    .select("roles(name)")
    .eq("user_id", auth.userId);

  const userRoles = (roleAssignments ?? [])
    .map((r: Record<string, unknown>) => {
      const role = r.roles as Record<string, unknown> | null;
      return role?.name as string | undefined;
    })
    .filter(Boolean) as string[];

  if (userRoles.length > 0) {
    const { data: perms } = await sb
      .from("report_role_permissions")
      .select("role_name")
      .eq("report_definition_id", reportDef.id)
      .in("role_name", userRoles);

    if (!perms || perms.length === 0) {
      return json({ error: "No permission for this report" }, 403);
    }
  } else {
    return json({ error: "No permission for this report" }, 403);
  }

  // 5. Check registry
  const reportFn = REGISTRY[reportKey];
  if (!reportFn) {
    return json({ error: "Report not implemented" }, 400);
  }

  // 6. Create job row
  const { data: job, error: insertError } = await sb
    .from("generated_reports")
    .insert({
      organization_id: auth.orgId,
      report_definition_id: reportDef.id,
      created_by: auth.userId,
      report_config: config,
      status: "generating",
      format,
    })
    .select("id")
    .single();

  if (insertError || !job) {
    console.error("[generate-report] Insert error:", insertError?.message);
    return json({ error: "Failed to create report job" }, 500);
  }

  const jobId = job.id as string;

  try {
    // 7. Get visible org IDs (apply config.org_ids filter if present)
    let orgIds = await getVisibleOrgIds(sb, auth.orgId);
    if (config.org_ids?.length) {
      const allowed = new Set(orgIds);
      orgIds = config.org_ids.filter((id) => allowed.has(id));
    }

    // 8. Run report
    const result = await reportFn(sb, orgIds, config);

    // 9. Generate CSV
    const csv = toCsv(result.columns, result.rows);
    const csvBytes = new TextEncoder().encode(csv);

    // 10. Upload to storage
    const dateStr = new Date().toISOString().split("T")[0];
    const num = String(reportDef.report_number).padStart(3, "0");
    const fileName = `RPT-${num}-${dateStr}.csv`;
    const storagePath = `${auth.orgId}/${reportKey}/${fileName}`;

    const { error: uploadError } = await sb.storage
      .from("generated-reports")
      .upload(storagePath, csvBytes, {
        contentType: "text/csv; charset=utf-8",
        upsert: true,
      });
    if (uploadError) throw new Error(`Upload failed: ${uploadError.message}`);

    // 11. Update job as complete
    await sb
      .from("generated_reports")
      .update({
        status: "complete",
        file_path_csv: storagePath,
        file_size_bytes: csvBytes.length,
        row_count: result.rows.length,
        data_quality_flags: result.flags,
        completed_at: new Date().toISOString(),
      })
      .eq("id", jobId);

    // 12. Audit log (fire-and-forget)
    sb.from("audit_log")
      .insert({
        user_id: auth.userId,
        organization_id: auth.orgId,
        action: "report_generated",
        module: "reports",
        table_name: "generated_reports",
        record_id: jobId,
        description: JSON.stringify({
          report_key: reportKey,
          format,
          row_count: result.rows.length,
        }),
        created_at: new Date().toISOString(),
      })
      .then(({ error: auditErr }) => {
        if (auditErr) console.warn("[generate-report] Audit log failed:", auditErr.message);
      })
      .catch((err: unknown) => {
        console.warn("[generate-report] Audit log exception:", err);
      });

    return json({ success: true, job_id: jobId });
  } catch (err) {
    const rawMsg = err instanceof Error ? err.message : "Report generation failed";
    // Truncate to prevent schema info leakage in stored error
    const message = rawMsg.length > 500 ? rawMsg.slice(0, 500) : rawMsg;
    console.error("[generate-report] Error:", message);

    // Update job as failed
    await sb
      .from("generated_reports")
      .update({
        status: "failed",
        error_message: message,
        completed_at: new Date().toISOString(),
      })
      .eq("id", jobId);

    // Return job_id so frontend can poll and see the failure state
    return json({ success: false, job_id: jobId, error: "Report generation failed" });
  }
});
